apiVersion: v1
items:
- apiVersion: v1
  data:
    systemd.lua: "function add_time(tag, timestamp, record)\n  new_record = {}\n  timeStr
      = os.date(\"!*t\", timestamp[\"sec\"])\n  t = string.format(\"%4d-%02d-%02dT%02d:%02d:%02d.%sZ\",\n\t\ttimeStr[\"year\"],
      timeStr[\"month\"], timeStr[\"day\"],\n\t\ttimeStr[\"hour\"], timeStr[\"min\"],
      timeStr[\"sec\"],\n\t\ttimestamp[\"nsec\"])\n  kubernetes = {}\n  kubernetes[\"pod_name\"]
      = record[\"_HOSTNAME\"]\n  kubernetes[\"container_name\"] = record[\"SYSLOG_IDENTIFIER\"]\n
      \ kubernetes[\"namespace_name\"] = \"kube-system\"\n  new_record[\"time\"] =
      t\n  new_record[\"log\"] = record[\"MESSAGE\"]\n  new_record[\"kubernetes\"]
      = kubernetes\n  return 1, timestamp, new_record\nend\n"
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"systemd.lua":"function add_time(tag, timestamp, record)\n  new_record = {}\n  timeStr = os.date(\"!*t\", timestamp[\"sec\"])\n  t = string.format(\"%4d-%02d-%02dT%02d:%02d:%02d.%sZ\",\n\t\ttimeStr[\"year\"], timeStr[\"month\"], timeStr[\"day\"],\n\t\ttimeStr[\"hour\"], timeStr[\"min\"], timeStr[\"sec\"],\n\t\ttimestamp[\"nsec\"])\n  kubernetes = {}\n  kubernetes[\"pod_name\"] = record[\"_HOSTNAME\"]\n  kubernetes[\"container_name\"] = record[\"SYSLOG_IDENTIFIER\"]\n  kubernetes[\"namespace_name\"] = \"kube-system\"\n  new_record[\"time\"] = t\n  new_record[\"log\"] = record[\"MESSAGE\"]\n  new_record[\"kubernetes\"] = kubernetes\n  return 1, timestamp, new_record\nend\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"operator","app.kubernetes.io/name":"fluent-bit-lua"},"name":"fluent-bit-lua","namespace":"kubesphere-logging-system"}}
    creationTimestamp: "2025-03-04T08:41:05Z"
    labels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/name: fluent-bit-lua
    name: fluent-bit-lua
    namespace: kubesphere-logging-system
    resourceVersion: "11874920"
    uid: 1ffd5539-cec7-4178-96e4-3b99d6558820
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIBGpEgb8zVRswDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNTAyMDcwNzU0MDZaFw0zNTAyMDUwNzU5MDZaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQDcKXkUtHMKM7qeci7OlLNez2FlydMAt9l6KKkywvtuLyaMIrJKbFPh8hml
      H2dnMm7PRXcy/xoZFucFHfjaUY+euYJ6cf3MAoQfG/SfgpA5TRqEPbdxwc+GHDy7
      6ZoH9gIYHLkdeRUw0QTKKZTNYmRhRZ7oLjRmssL0kSpWOrg3EdN/K95ZT4eczUrl
      ts/rLLJPILP6LuWGllkIqnKBpm95RbpeGfTCoCAYbYIpbm0XzbybHeJuar+mA2kG
      Vhv8LJH9HIUCPTPLY4eUNFM5yAOlqR4p2tKpIHcaQC8WZhJqQBd3/OLx1fDnEsu5
      KCg99V39QHNmXONGKNdVZdnvCa8DAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRSbsFhjuaavB3D2AJAgY6/Kg93NDAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQBtFumnVigF
      ZqgHe3ok8jdx/o48sBfKM+N+eiqEKsuVuWhiYcMGhlXqqvgX5qHDcM+QPC2x4QxE
      NiZ0beIXwVs/xeOx9KeoPfnem58Ke51qlCBiTZrPTFhCIGUfqpD9SAxFRXX/4Re+
      ff8hORHxXHM+mo9fRUIsDkEON3IoFbImuq0bfklHbPfFJ1z+f/Fg+3bG4bUcMRDG
      /N3BorYqcnQxsvXlZpw3yDQrm3VukCTZSKm3FAuakJlBntmxHM4UewnN0VaF8ZAR
      dfz/NBVYyrEu/zPNPOYYHVLLfcMPbtlxnCnQuBB5C6Bv0hH1YNcwvEObxZH4+8G0
      O6YN95NGdZMw
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2025-03-04T08:39:59Z"
    name: kube-root-ca.crt
    namespace: kubesphere-logging-system
    resourceVersion: "11874005"
    uid: 341fb2a7-96c0-4320-9ff7-ab80858c098c
- apiVersion: v1
  data:
    opensearch.yml: |
      cluster.name: opensearch-cluster
      network.host: 0.0.0.0
      plugins:
        security:
          ssl:
            transport:
              pemcert_filepath: esnode.pem
              pemkey_filepath: esnode-key.pem
              pemtrustedcas_filepath: root-ca.pem
              enforce_hostname_verification: false
            http:
              enabled: true
              pemcert_filepath: esnode.pem
              pemkey_filepath: esnode-key.pem
              pemtrustedcas_filepath: root-ca.pem
          allow_unsafe_democertificates: true
          allow_default_init_securityindex: true
          authcz:
            admin_dn:
              - CN=kirk,OU=client,O=client,L=test,C=de
          audit.type: internal_opensearch
          enable_snapshot_restore_privilege: true
          check_snapshot_restore_write_privileges: true
          restapi:
            roles_enabled: ["all_access", "security_rest_api_access"]
          system_indices:
            enabled: true
            indices:
              [
                ".opendistro-alerting-config",
                ".opendistro-alerting-alert*",
                ".opendistro-anomaly-results*",
                ".opendistro-anomaly-detector*",
                ".opendistro-anomaly-checkpoints",
                ".opendistro-anomaly-detection-state",
                ".opendistro-reports-*",
                ".opendistro-notifications-*",
                ".opendistro-notebooks",
                ".opendistro-asynchronous-search-response*",
              ]
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: opensearch-data
      meta.helm.sh/release-namespace: kubesphere-logging-system
    creationTimestamp: "2025-03-04T08:40:52Z"
    labels:
      app.kubernetes.io/component: opensearch-cluster-data
      app.kubernetes.io/instance: opensearch-data
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: opensearch
      app.kubernetes.io/version: 2.6.0
      helm.sh/chart: opensearch-2.11.0
    name: opensearch-cluster-data-config
    namespace: kubesphere-logging-system
    resourceVersion: "11874531"
    uid: 352ac8a9-a996-48a6-908e-358f5edfd3fe
- apiVersion: v1
  data:
    opensearch.yml: |
      cluster.name: opensearch-cluster

      # Bind to all interfaces because we don't know what IP address Docker will assign to us.
      network.host: 0.0.0.0
      plugins:
        security:
          ssl:
            transport:
              pemcert_filepath: esnode.pem
              pemkey_filepath: esnode-key.pem
              pemtrustedcas_filepath: root-ca.pem
              enforce_hostname_verification: false
            http:
              enabled: true
              pemcert_filepath: esnode.pem
              pemkey_filepath: esnode-key.pem
              pemtrustedcas_filepath: root-ca.pem
          allow_unsafe_democertificates: true
          allow_default_init_securityindex: true
          authcz:
            admin_dn:
              - CN=kirk,OU=client,O=client,L=test,C=de
          audit.type: internal_opensearch
          enable_snapshot_restore_privilege: true
          check_snapshot_restore_write_privileges: true
          restapi:
            roles_enabled: ["all_access", "security_rest_api_access"]
          system_indices:
            enabled: true
            indices:
              [
                ".opendistro-alerting-config",
                ".opendistro-alerting-alert*",
                ".opendistro-anomaly-results*",
                ".opendistro-anomaly-detector*",
                ".opendistro-anomaly-checkpoints",
                ".opendistro-anomaly-detection-state",
                ".opendistro-reports-*",
                ".opendistro-notifications-*",
                ".opendistro-notebooks",
                ".opendistro-asynchronous-search-response*",
              ]
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: opensearch-master
      meta.helm.sh/release-namespace: kubesphere-logging-system
    creationTimestamp: "2025-03-04T08:40:41Z"
    labels:
      app.kubernetes.io/component: opensearch-cluster-master
      app.kubernetes.io/instance: opensearch-master
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: opensearch
      app.kubernetes.io/version: 2.6.0
      helm.sh/chart: opensearch-2.11.0
    name: opensearch-cluster-master-config
    namespace: kubesphere-logging-system
    resourceVersion: "11874408"
    uid: b5aa3886-cc93-40c4-bdcd-0e22cecfd806
- apiVersion: v1
  data:
    action_file.yml: |-
      ---
      actions:
        1:
          action: delete_indices
          description: "Clean up opensearch by deleting old logging indices"
          options:
            timeout_override:
            continue_if_exception: False
            disable_action: False
            ignore_empty_list: True
          filters:
          - filtertype: pattern
            kind: prefix
            value: ks-whizard-logging
            exclude: False
          - filtertype: age
            source: name
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 7
            field:
            stats_result:
            epoch:
            exclude: False
        2:
          action: delete_indices
          description: "Clean up opensearch by deleting old events indices"
          options:
            timeout_override:
            continue_if_exception: False
            disable_action: False
            ignore_empty_list: True
          filters:
          - filtertype: pattern
            kind: prefix
            value: ks-whizard-events
            exclude: False
          - filtertype: age
            source: name
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 7
            field:
            stats_result:
            epoch:
            exclude: False
        3:
          action: delete_indices
          description: "Clean up opensearch by deleting old auditing indices"
          options:
            timeout_override:
            continue_if_exception: False
            disable_action: False
            ignore_empty_list: True
          filters:
          - filtertype: pattern
            kind: prefix
            value: ks-whizard-auditing
            exclude: False
          - filtertype: age
            source: name
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 7
            field:
            stats_result:
            epoch:
            exclude: False
        4:
          action: delete_indices
          description: "Clean up opensearch by deleting old istio indices"
          options:
            timeout_override:
            continue_if_exception: False
            disable_action: False
            ignore_empty_list: True
          filters:
          - filtertype: pattern
            kind: prefix
            value: whizard
            exclude: False
          - filtertype: age
            source: name
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 7
            field:
            stats_result:
            epoch:
            exclude: False
    config.yml: "---\nclient:\n  hosts:\n    - opensearch-cluster-data.kubesphere-logging-system.svc\n
      \ port: 9200      \n  # url_prefix:\n  use_ssl: True\n  # certificate:\n  #
      client_cert:\n  # client_key:\n  ssl_no_validate: True\n  http_auth: admin:admin\n
      \ # http_auth:\n  # timeout: 30\n  # master_only: False\n# logging:\n#   loglevel:
      INFO\n#   logfile:\n#   logformat: default\n#   blacklist: ['elasticsearch',
      'urllib3']"
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: opensearch-logging-curator
      meta.helm.sh/release-namespace: kubesphere-logging-system
    creationTimestamp: "2025-03-04T08:40:44Z"
    labels:
      app: opensearch-curator
      app.kubernetes.io/managed-by: Helm
      chart: opensearch-curator-0.0.5
      heritage: Helm
      release: opensearch-logging-curator
    name: opensearch-logging-curator-opensearch-curator-config
    namespace: kubesphere-logging-system
    resourceVersion: "11874703"
    uid: c9d13dca-6e8f-4e5b-8215-eb2a234a3b6d
kind: List
metadata:
  resourceVersion: ""
