apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      majorVersion: "2"
      meta.helm.sh/release-name: opensearch-data
      meta.helm.sh/release-namespace: kubesphere-logging-system
    creationTimestamp: "2025-03-04T08:40:52Z"
    generation: 3
    labels:
      app.kubernetes.io/component: opensearch-cluster-data
      app.kubernetes.io/instance: opensearch-data
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: opensearch
      app.kubernetes.io/version: 2.6.0
      helm.sh/chart: opensearch-2.11.0
    name: opensearch-cluster-data
    namespace: kubesphere-logging-system
    resourceVersion: "72247727"
    uid: d43daa48-f995-4b6c-bf07-413d72c8f3ba
  spec:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
    podManagementPolicy: Parallel
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: opensearch-data
        app.kubernetes.io/name: opensearch
    serviceName: opensearch-cluster-data-headless
    template:
      metadata:
        annotations:
          configchecksum: 7ae9ee8976556684117227f195eef403383946c42d4a80240e54080c8fb0393
          kubectl.kubernetes.io/restartedAt: "2025-04-25T13:01:16+05:30"
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: opensearch-cluster-data
          app.kubernetes.io/instance: opensearch-data
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: opensearch
          app.kubernetes.io/version: 2.6.0
          helm.sh/chart: opensearch-2.11.0
        name: opensearch-cluster-data
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                    - opensearch-data
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - opensearch
                topologyKey: kubernetes.io/hostname
              weight: 1
        containers:
        - env:
          - name: node.name
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: opensearch-cluster-master-headless
          - name: cluster.name
            value: opensearch-cluster
          - name: network.host
            value: 0.0.0.0
          - name: OPENSEARCH_JAVA_OPTS
            value: -Xmx1536M -Xms1536M
          - name: node.roles
            value: ingest,data,remote_cluster_client,
          image: opensearchproject/opensearch:2.6.0
          imagePullPolicy: IfNotPresent
          name: opensearch
          ports:
          - containerPort: 9200
            name: http
            protocol: TCP
          - containerPort: 9300
            name: transport
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 9200
            timeoutSeconds: 3
          resources:
            requests:
              cpu: "1"
              memory: 1536Mi
          securityContext:
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
            runAsUser: 1000
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9200
            timeoutSeconds: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /usr/share/opensearch/data
            name: opensearch-cluster-data
          - mountPath: /usr/share/opensearch/config/opensearch.yml
            name: config
            subPath: opensearch.yml
        dnsPolicy: ClusterFirst
        enableServiceLinks: true
        initContainers:
        - args:
          - chown -R 1000:1000 /usr/share/opensearch/data
          command:
          - sh
          - -c
          image: busybox:latest
          imagePullPolicy: Always
          name: fsgroup-volume
          resources: {}
          securityContext:
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /usr/share/opensearch/data
            name: opensearch-cluster-data
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1000
          runAsUser: 1000
        terminationGracePeriodSeconds: 120
        volumes:
        - configMap:
            defaultMode: 420
            name: opensearch-cluster-data-config
          name: config
    updateStrategy:
      type: RollingUpdate
    volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: opensearch-cluster-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        volumeMode: Filesystem
      status:
        phase: Pending
  status:
    availableReplicas: 2
    collisionCount: 0
    currentReplicas: 2
    currentRevision: opensearch-cluster-data-8b8964d67
    observedGeneration: 3
    readyReplicas: 2
    replicas: 2
    updateRevision: opensearch-cluster-data-8b8964d67
    updatedReplicas: 2
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      majorVersion: "2"
      meta.helm.sh/release-name: opensearch-master
      meta.helm.sh/release-namespace: kubesphere-logging-system
    creationTimestamp: "2025-03-04T08:40:41Z"
    generation: 3
    labels:
      app.kubernetes.io/component: opensearch-cluster-master
      app.kubernetes.io/instance: opensearch-master
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: opensearch
      app.kubernetes.io/version: 2.6.0
      helm.sh/chart: opensearch-2.11.0
    name: opensearch-cluster-master
    namespace: kubesphere-logging-system
    resourceVersion: "72247667"
    uid: 02876eb4-d790-4e1f-b787-812b274eddf5
  spec:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
    podManagementPolicy: Parallel
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: opensearch-master
        app.kubernetes.io/name: opensearch
    serviceName: opensearch-cluster-master-headless
    template:
      metadata:
        annotations:
          configchecksum: eb70eea659188d444ae38c6d48b6cce2f1c6bd3d9a4b073c07f3839a50e6a01
          kubectl.kubernetes.io/restartedAt: "2025-04-25T13:01:23+05:30"
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: opensearch-cluster-master
          app.kubernetes.io/instance: opensearch-master
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: opensearch
          app.kubernetes.io/version: 2.6.0
          helm.sh/chart: opensearch-2.11.0
        name: opensearch-cluster-master
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                    - opensearch-master
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - opensearch
                topologyKey: kubernetes.io/hostname
              weight: 1
        containers:
        - env:
          - name: node.name
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: cluster.initial_master_nodes
            value: opensearch-cluster-master-0,opensearch-cluster-master-1,opensearch-cluster-master-2,
          - name: discovery.seed_hosts
            value: opensearch-cluster-master-headless
          - name: cluster.name
            value: opensearch-cluster
          - name: network.host
            value: 0.0.0.0
          - name: OPENSEARCH_JAVA_OPTS
            value: -Xmx512M -Xms512M
          - name: node.roles
            value: master,
          image: opensearchproject/opensearch:2.6.0
          imagePullPolicy: IfNotPresent
          name: opensearch
          ports:
          - containerPort: 9200
            name: http
            protocol: TCP
          - containerPort: 9300
            name: transport
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 9200
            timeoutSeconds: 3
          resources:
            requests:
              cpu: "1"
              memory: 512Mi
          securityContext:
            capabilities:
              drop:
              - ALL
            runAsNonRoot: true
            runAsUser: 1000
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9200
            timeoutSeconds: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /usr/share/opensearch/data
            name: opensearch-cluster-master
          - mountPath: /usr/share/opensearch/config/opensearch.yml
            name: config
            subPath: opensearch.yml
        dnsPolicy: ClusterFirst
        enableServiceLinks: true
        initContainers:
        - args:
          - chown -R 1000:1000 /usr/share/opensearch/data
          command:
          - sh
          - -c
          image: busybox:latest
          imagePullPolicy: Always
          name: fsgroup-volume
          resources: {}
          securityContext:
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /usr/share/opensearch/data
            name: opensearch-cluster-master
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1000
          runAsUser: 1000
        terminationGracePeriodSeconds: 120
        volumes:
        - configMap:
            defaultMode: 420
            name: opensearch-cluster-master-config
          name: config
    updateStrategy:
      type: RollingUpdate
    volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: opensearch-cluster-master
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
        volumeMode: Filesystem
      status:
        phase: Pending
  status:
    availableReplicas: 3
    collisionCount: 0
    currentReplicas: 3
    currentRevision: opensearch-cluster-master-856cd98799
    observedGeneration: 3
    readyReplicas: 3
    replicas: 3
    updateRevision: opensearch-cluster-master-856cd98799
    updatedReplicas: 3
kind: List
metadata:
  resourceVersion: ""
