apiVersion: v1
items:
- apiVersion: v1
  data:
    Corefile: ".:53 {\n    # fix dns resolution errors for some specific domains\n
      \   bufsize 1024      \n    errors\n    health {\n       lameduck 5s\n    }\n
      \   ready\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n       pods
      insecure\n       fallthrough in-addr.arpa ip6.arpa\n       ttl 30\n    }\n    prometheus
      :9153\n    forward . /etc/resolv.conf {\n       max_concurrent 2000\n    }\n
      \   cache 30\n    loop\n    reload\n    loadbalance\n}\n"
  kind: ConfigMap
  metadata:
    creationTimestamp: "2025-02-07T07:59:17Z"
    name: coredns
    namespace: kube-system
    resourceVersion: "40695081"
    uid: 3af96490-a931-4007-80d7-a8c9ed561a4a
- apiVersion: v1
  data:
    client-ca-file: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIBGpEgb8zVRswDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNTAyMDcwNzU0MDZaFw0zNTAyMDUwNzU5MDZaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQDcKXkUtHMKM7qeci7OlLNez2FlydMAt9l6KKkywvtuLyaMIrJKbFPh8hml
      H2dnMm7PRXcy/xoZFucFHfjaUY+euYJ6cf3MAoQfG/SfgpA5TRqEPbdxwc+GHDy7
      6ZoH9gIYHLkdeRUw0QTKKZTNYmRhRZ7oLjRmssL0kSpWOrg3EdN/K95ZT4eczUrl
      ts/rLLJPILP6LuWGllkIqnKBpm95RbpeGfTCoCAYbYIpbm0XzbybHeJuar+mA2kG
      Vhv8LJH9HIUCPTPLY4eUNFM5yAOlqR4p2tKpIHcaQC8WZhJqQBd3/OLx1fDnEsu5
      KCg99V39QHNmXONGKNdVZdnvCa8DAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRSbsFhjuaavB3D2AJAgY6/Kg93NDAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQBtFumnVigF
      ZqgHe3ok8jdx/o48sBfKM+N+eiqEKsuVuWhiYcMGhlXqqvgX5qHDcM+QPC2x4QxE
      NiZ0beIXwVs/xeOx9KeoPfnem58Ke51qlCBiTZrPTFhCIGUfqpD9SAxFRXX/4Re+
      ff8hORHxXHM+mo9fRUIsDkEON3IoFbImuq0bfklHbPfFJ1z+f/Fg+3bG4bUcMRDG
      /N3BorYqcnQxsvXlZpw3yDQrm3VukCTZSKm3FAuakJlBntmxHM4UewnN0VaF8ZAR
      dfz/NBVYyrEu/zPNPOYYHVLLfcMPbtlxnCnQuBB5C6Bv0hH1YNcwvEObxZH4+8G0
      O6YN95NGdZMw
      -----END CERTIFICATE-----
    requestheader-allowed-names: '["front-proxy-client"]'
    requestheader-client-ca-file: |
      -----BEGIN CERTIFICATE-----
      MIIDETCCAfmgAwIBAgIIRMd5XKXev1cwDQYJKoZIhvcNAQELBQAwGTEXMBUGA1UE
      AxMOZnJvbnQtcHJveHktY2EwHhcNMjUwMjA3MDc1NDA2WhcNMzUwMjA1MDc1OTA2
      WjAZMRcwFQYDVQQDEw5mcm9udC1wcm94eS1jYTCCASIwDQYJKoZIhvcNAQEBBQAD
      ggEPADCCAQoCggEBAMMonC9pya00zTL55VUZUrgXBhZ7bvb4rVV/AcNM+FMebHry
      WVvS41B11wKzvAhtpiv/vG+1ZUqQztRHYdBLB/OwjOmOYB98dA0QeG3PcLx1OlN3
      gUzn00tZ/oBuIdNaSKO9cZFeraqkMmaOqzVpoJh04TorKtwc3NNZuz8YAgrzCFmW
      PowrzNLDPPr7SXWPWh2BGBLe9fJroZ6QFXwWP3jbfGoP04mLmfS01vezX/agunz/
      ogSs0JM4npQ1XCZYFfo9F/6inkK45Gb/7rd5kIpATuaHxOgsClFeAOFHu3E7WQvP
      rbpbwK1GoMlviNOenAD1mMlfhXxutzIP/8ynjzsCAwEAAaNdMFswDgYDVR0PAQH/
      BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMEdtU20n9k1fBblVuus
      QAUsvNttMBkGA1UdEQQSMBCCDmZyb250LXByb3h5LWNhMA0GCSqGSIb3DQEBCwUA
      A4IBAQAdKB2KQwmXSJReSKwS0blo0GLUlWHlWpuBSMO3vdZ5LBtKzQyw9wdqLHll
      4h/8S62QgaU9XDt4JiYFl34U8AxM5ruEvTu93SyTVry4fZ7sZBZ2KOGl7PvD/fvp
      grKDf2FsPD7jL6YAT3cdRQcxlz6wzh+2NUvSEdpe+3sOs1ZRYC9ppq4q4xEYzM/i
      VVLLdrwD1Bh4YRCz+5PvJW2SLV7O5PA45kHwfZzCNLTPQ1gqsaxKrdrhA1/REeTQ
      TegCTEJm1Iosgfqwggm6h+xHc6GxzpdXwBgakknMgqy0j6RF2vWmOPMNqOYfHlxx
      LEI24BqrNPdr8npUk9ZTrPR0mqgL
      -----END CERTIFICATE-----
    requestheader-extra-headers-prefix: '["X-Remote-Extra-"]'
    requestheader-group-headers: '["X-Remote-Group"]'
    requestheader-username-headers: '["X-Remote-User"]'
  kind: ConfigMap
  metadata:
    creationTimestamp: "2025-02-07T07:59:13Z"
    name: extension-apiserver-authentication
    namespace: kube-system
    resourceVersion: "25"
    uid: f625edcf-f0c2-4ff0-a871-3006bb8baf8d
- apiVersion: v1
  data:
    since: "2025-02-07"
  kind: ConfigMap
  metadata:
    creationTimestamp: "2025-02-07T07:59:13Z"
    name: kube-apiserver-legacy-service-account-token-tracking
    namespace: kube-system
    resourceVersion: "42"
    uid: 589931e8-73a2-467f-bd16-9188e7a01c31
- apiVersion: v1
  data:
    config.conf: "apiVersion: kubeproxy.config.k8s.io/v1alpha1\nbindAddress: 0.0.0.0\nbindAddressHardFail:
      false\nclientConnection:\n  acceptContentTypes: \"\"\n  burst: 0\n  contentType:
      \"\"\n  kubeconfig: /var/lib/kube-proxy/kubeconfig.conf\n  qps: 0\nclusterCIDR:
      192.168.0.0/16\nconfigSyncPeriod: 0s\nconntrack:\n  maxPerCore: null\n  min:
      null\n  tcpBeLiberal: false\n  tcpCloseWaitTimeout: null\n  tcpEstablishedTimeout:
      null\n  udpStreamTimeout: 0s\n  udpTimeout: 0s\ndetectLocal:\n  bridgeInterface:
      \"\"\n  interfaceNamePrefix: \"\"\ndetectLocalMode: \"\"\nenableProfiling: false\nhealthzBindAddress:
      \"\"\nhostnameOverride: \"\"\niptables:\n  localhostNodePorts: null\n  masqueradeAll:
      false\n  masqueradeBit: null\n  minSyncPeriod: 0s\n  syncPeriod: 0s\nipvs:\n
      \ excludeCIDRs: null\n  minSyncPeriod: 0s\n  scheduler: \"\"\n  strictARP: false\n
      \ syncPeriod: 0s\n  tcpFinTimeout: 0s\n  tcpTimeout: 0s\n  udpTimeout: 0s\nkind:
      KubeProxyConfiguration\nmode: \"ipvs\"\nipvs:\n  strictARP: true  \nlogging:\n
      \ flushFrequency: 0\n  options:\n    json:\n      infoBufferSize: \"0\"\n    text:\n
      \     infoBufferSize: \"0\"\n  verbosity: 0\nmetricsBindAddress: \"\"\nmode:
      \"\"\nnftables:\n  masqueradeAll: false\n  masqueradeBit: null\n  minSyncPeriod:
      0s\n  syncPeriod: 0s\nnodePortAddresses: null\noomScoreAdj: null\nportRange:
      \"\"\nshowHiddenMetricsForVersion: \"\"\nwinkernel:\n  enableDSR: false\n  forwardHealthCheckVip:
      false\n  networkName: \"\"\n  rootHnsEndpointName: \"\"\n  sourceVip: \"\""
    kubeconfig.conf: |-
      apiVersion: v1
      kind: Config
      clusters:
      - cluster:
          certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          server: https://10.48.219.134:6443
        name: default
      contexts:
      - context:
          cluster: default
          namespace: default
          user: default
        name: default
      current-context: default
      users:
      - name: default
        user:
          tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  kind: ConfigMap
  metadata:
    annotations:
      kubeadm.kubernetes.io/component-config.hash: sha256:02fc9e166e3737c7e4bf3a476bc81ba8ce9265553a9e79aadebb2bb7e513bf43
    creationTimestamp: "2025-02-07T07:59:18Z"
    labels:
      app: kube-proxy
    name: kube-proxy
    namespace: kube-system
    resourceVersion: "25989"
    uid: 2e4ce13a-de85-49b2-aec3-bf198eaf2210
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIBGpEgb8zVRswDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNTAyMDcwNzU0MDZaFw0zNTAyMDUwNzU5MDZaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQDcKXkUtHMKM7qeci7OlLNez2FlydMAt9l6KKkywvtuLyaMIrJKbFPh8hml
      H2dnMm7PRXcy/xoZFucFHfjaUY+euYJ6cf3MAoQfG/SfgpA5TRqEPbdxwc+GHDy7
      6ZoH9gIYHLkdeRUw0QTKKZTNYmRhRZ7oLjRmssL0kSpWOrg3EdN/K95ZT4eczUrl
      ts/rLLJPILP6LuWGllkIqnKBpm95RbpeGfTCoCAYbYIpbm0XzbybHeJuar+mA2kG
      Vhv8LJH9HIUCPTPLY4eUNFM5yAOlqR4p2tKpIHcaQC8WZhJqQBd3/OLx1fDnEsu5
      KCg99V39QHNmXONGKNdVZdnvCa8DAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRSbsFhjuaavB3D2AJAgY6/Kg93NDAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQBtFumnVigF
      ZqgHe3ok8jdx/o48sBfKM+N+eiqEKsuVuWhiYcMGhlXqqvgX5qHDcM+QPC2x4QxE
      NiZ0beIXwVs/xeOx9KeoPfnem58Ke51qlCBiTZrPTFhCIGUfqpD9SAxFRXX/4Re+
      ff8hORHxXHM+mo9fRUIsDkEON3IoFbImuq0bfklHbPfFJ1z+f/Fg+3bG4bUcMRDG
      /N3BorYqcnQxsvXlZpw3yDQrm3VukCTZSKm3FAuakJlBntmxHM4UewnN0VaF8ZAR
      dfz/NBVYyrEu/zPNPOYYHVLLfcMPbtlxnCnQuBB5C6Bv0hH1YNcwvEObxZH4+8G0
      O6YN95NGdZMw
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2025-02-07T07:59:29Z"
    name: kube-root-ca.crt
    namespace: kube-system
    resourceVersion: "331"
    uid: 9df641f2-f35d-4a70-8f0d-7a59b48bc2f2
- apiVersion: v1
  data:
    ClusterConfiguration: |
      apiServer:
        timeoutForControlPlane: 4m0s
      apiVersion: kubeadm.k8s.io/v1beta3
      certificatesDir: /etc/kubernetes/pki
      clusterName: kubernetes
      controlPlaneEndpoint: 10.48.219.134:6443
      controllerManager: {}
      dns: {}
      etcd:
        local:
          dataDir: /var/lib/etcd
      imageRepository: registry.k8s.io
      kind: ClusterConfiguration
      kubernetesVersion: v1.30.9
      networking:
        dnsDomain: cluster.local
        podSubnet: 192.168.0.0/16
        serviceSubnet: 10.96.0.0/12
      scheduler: {}
  kind: ConfigMap
  metadata:
    creationTimestamp: "2025-02-07T07:59:15Z"
    name: kubeadm-config
    namespace: kube-system
    resourceVersion: "210"
    uid: eb96ed95-5584-4374-953f-95250ae443e1
- apiVersion: v1
  data:
    kubelet: |
      apiVersion: kubelet.config.k8s.io/v1beta1
      authentication:
        anonymous:
          enabled: false
        webhook:
          cacheTTL: 0s
          enabled: true
        x509:
          clientCAFile: /etc/kubernetes/pki/ca.crt
      authorization:
        mode: Webhook
        webhook:
          cacheAuthorizedTTL: 0s
          cacheUnauthorizedTTL: 0s
      cgroupDriver: systemd
      clusterDNS:
      - 10.96.0.10
      clusterDomain: cluster.local
      containerRuntimeEndpoint: ""
      cpuManagerReconcilePeriod: 0s
      evictionPressureTransitionPeriod: 0s
      fileCheckFrequency: 0s
      healthzBindAddress: 127.0.0.1
      healthzPort: 10248
      httpCheckFrequency: 0s
      imageMaximumGCAge: 0s
      imageMinimumGCAge: 0s
      kind: KubeletConfiguration
      logging:
        flushFrequency: 0
        options:
          json:
            infoBufferSize: "0"
          text:
            infoBufferSize: "0"
        verbosity: 0
      memorySwap: {}
      nodeStatusReportFrequency: 0s
      nodeStatusUpdateFrequency: 0s
      rotateCertificates: true
      runtimeRequestTimeout: 0s
      shutdownGracePeriod: 0s
      shutdownGracePeriodCriticalPods: 0s
      staticPodPath: /etc/kubernetes/manifests
      streamingConnectionIdleTimeout: 0s
      syncFrequency: 0s
      volumeStatsAggPeriod: 0s
  kind: ConfigMap
  metadata:
    annotations:
      kubeadm.kubernetes.io/component-config.hash: sha256:899c230cbcdf566dbb9a10f53cb164093ffdf06654cb687a43698e4215a04c4b
    creationTimestamp: "2025-02-07T07:59:15Z"
    name: kubelet-config
    namespace: kube-system
    resourceVersion: "213"
    uid: 26ca6652-e0a9-4523-851b-33a55d41e5b1
kind: List
metadata:
  resourceVersion: ""
