apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "2"
      deployment.kubernetes.io/max-replicas: "3"
      deployment.kubernetes.io/revision: "2"
    creationTimestamp: "2025-02-19T14:35:38Z"
    generation: 2
    labels:
      app: redis
      pod-template-hash: 594bb96598
    name: redis-594bb96598
    namespace: redis
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: redis
      uid: 7bc53e87-c4fe-40b0-a284-a4f87e24c9ee
    resourceVersion: "72238727"
    uid: 8a852391-6299-4ce4-b063-b4c662ad3a7f
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: redis
        pod-template-hash: 594bb96598
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: redis
          pod-template-hash: 594bb96598
      spec:
        containers:
        - command:
          - redis-server
          - --requirepass
          - $(REDIS_PASSWORD)
          env:
          - name: REDIS_PASSWORD
            value: ogJ4MKWbh0
          image: redis:latest
          imagePullPolicy: Always
          name: redis
          ports:
          - containerPort: 6379
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    fullyLabeledReplicas: 2
    observedGeneration: 2
    readyReplicas: 2
    replicas: 2
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-02-19T14:29:25Z"
    generation: 2
    labels:
      app: redis
      pod-template-hash: 6b5bcbb6b6
    name: redis-6b5bcbb6b6
    namespace: redis
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: redis
      uid: 7bc53e87-c4fe-40b0-a284-a4f87e24c9ee
    resourceVersion: "5170953"
    uid: 97a61b03-0b69-4a07-aa24-f3f6b27b67d9
  spec:
    replicas: 0
    selector:
      matchLabels:
        app: redis
        pod-template-hash: 6b5bcbb6b6
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: redis
          pod-template-hash: 6b5bcbb6b6
      spec:
        containers:
        - image: redis:latest
          imagePullPolicy: Always
          name: redis
          ports:
          - containerPort: 6379
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    observedGeneration: 2
    replicas: 0
kind: List
metadata:
  resourceVersion: ""
