apiVersion: v1
items:
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-attacher
    usage:
      cpu: 111341n
      memory: 20360Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: csi-attacher
      pod-template-hash: 6fcbcb955
    name: csi-attacher-6fcbcb955-4zq8k
    namespace: longhorn-system
  timestamp: "2025-10-03T07:59:02Z"
  window: 13.526s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-attacher
    usage:
      cpu: 142359n
      memory: 17264Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: csi-attacher
      pod-template-hash: 6fcbcb955
    name: csi-attacher-6fcbcb955-l9gxh
    namespace: longhorn-system
  timestamp: "2025-10-03T07:58:54Z"
  window: 12.342s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-attacher
    usage:
      cpu: 212086n
      memory: 16936Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: csi-attacher
      pod-template-hash: 6fcbcb955
    name: csi-attacher-6fcbcb955-rlz68
    namespace: longhorn-system
  timestamp: "2025-10-03T07:59:05Z"
  window: 14.678s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-provisioner
    usage:
      cpu: 564443n
      memory: 11632Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: csi-provisioner
      pod-template-hash: 598bb7c5fb
    name: csi-provisioner-598bb7c5fb-26p4d
    namespace: longhorn-system
  timestamp: "2025-10-03T07:58:59Z"
  window: 17.364s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-provisioner
    usage:
      cpu: 756379n
      memory: 17916Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: csi-provisioner
      pod-template-hash: 598bb7c5fb
    name: csi-provisioner-598bb7c5fb-gdt7h
    namespace: longhorn-system
  timestamp: "2025-10-03T07:59:00Z"
  window: 17.281s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-provisioner
    usage:
      cpu: 427112n
      memory: 11312Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: csi-provisioner
      pod-template-hash: 598bb7c5fb
    name: csi-provisioner-598bb7c5fb-smgn8
    namespace: longhorn-system
  timestamp: "2025-10-03T07:59:05Z"
  window: 30.444s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-resizer
    usage:
      cpu: 117371n
      memory: 13440Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: csi-resizer
      pod-template-hash: 68d958d4b6
    name: csi-resizer-68d958d4b6-k9mcj
    namespace: longhorn-system
  timestamp: "2025-10-03T07:58:56Z"
  window: 15.157s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-resizer
    usage:
      cpu: 140602n
      memory: 12064Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: csi-resizer
      pod-template-hash: 68d958d4b6
    name: csi-resizer-68d958d4b6-ncw8g
    namespace: longhorn-system
  timestamp: "2025-10-03T07:59:01Z"
  window: 15.142s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-resizer
    usage:
      cpu: 1340905n
      memory: 19656Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: csi-resizer
      pod-template-hash: 68d958d4b6
    name: csi-resizer-68d958d4b6-vn9vp
    namespace: longhorn-system
  timestamp: "2025-10-03T07:58:50Z"
  window: 28.923s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-snapshotter
    usage:
      cpu: 121079n
      memory: 19908Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: csi-snapshotter
      pod-template-hash: 6b4f685f7d
    name: csi-snapshotter-6b4f685f7d-jsdpb
    namespace: longhorn-system
  timestamp: "2025-10-03T07:59:05Z"
  window: 20.276s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-snapshotter
    usage:
      cpu: 190580n
      memory: 15980Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: csi-snapshotter
      pod-template-hash: 6b4f685f7d
    name: csi-snapshotter-6b4f685f7d-msg9d
    namespace: longhorn-system
  timestamp: "2025-10-03T07:58:55Z"
  window: 11.911s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-snapshotter
    usage:
      cpu: 82253n
      memory: 21044Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: csi-snapshotter
      pod-template-hash: 6b4f685f7d
    name: csi-snapshotter-6b4f685f7d-qp5n8
    namespace: longhorn-system
  timestamp: "2025-10-03T07:59:04Z"
  window: 17.908s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: engine-image-ei-c2d50bcc
    usage:
      cpu: 11018376n
      memory: 26900Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      controller-revision-hash: 7756674b54
      longhorn.io/component: engine-image
      longhorn.io/engine-image: ei-c2d50bcc
      pod-template-generation: "1"
    name: engine-image-ei-c2d50bcc-2w74z
    namespace: longhorn-system
  timestamp: "2025-10-03T07:58:54Z"
  window: 19.155s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: engine-image-ei-c2d50bcc
    usage:
      cpu: 8795062n
      memory: 2200Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      controller-revision-hash: 7756674b54
      longhorn.io/component: engine-image
      longhorn.io/engine-image: ei-c2d50bcc
      pod-template-generation: "1"
    name: engine-image-ei-c2d50bcc-rqwsm
    namespace: longhorn-system
  timestamp: "2025-10-03T07:59:09Z"
  window: 18.43s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: engine-image-ei-c2d50bcc
    usage:
      cpu: 11651187n
      memory: 27552Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      controller-revision-hash: 7756674b54
      longhorn.io/component: engine-image
      longhorn.io/engine-image: ei-c2d50bcc
      pod-template-generation: "1"
    name: engine-image-ei-c2d50bcc-vjphp
    namespace: longhorn-system
  timestamp: "2025-10-03T07:58:40Z"
  window: 14.105s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: instance-manager
    usage:
      cpu: 42406447n
      memory: 484632Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      longhorn.io/component: instance-manager
      longhorn.io/data-engine: v1
      longhorn.io/instance-manager-image: imi-46d35c0a
      longhorn.io/instance-manager-type: aio
      longhorn.io/managed-by: longhorn-manager
      longhorn.io/node: zee8608workerapi03
    name: instance-manager-07ccad272ad0241589616ab358b3c6c2
    namespace: longhorn-system
  timestamp: "2025-10-03T07:58:44Z"
  window: 10.267s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: instance-manager
    usage:
      cpu: 52215842n
      memory: 484248Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      longhorn.io/component: instance-manager
      longhorn.io/data-engine: v1
      longhorn.io/instance-manager-image: imi-46d35c0a
      longhorn.io/instance-manager-type: aio
      longhorn.io/managed-by: longhorn-manager
      longhorn.io/node: zee8608workerapi01
    name: instance-manager-0d91d974e534c34183045b1d57ce4ece
    namespace: longhorn-system
  timestamp: "2025-10-03T07:58:56Z"
  window: 14.821s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: instance-manager
    usage:
      cpu: 43258033n
      memory: 563580Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      longhorn.io/component: instance-manager
      longhorn.io/data-engine: v1
      longhorn.io/instance-manager-image: imi-46d35c0a
      longhorn.io/instance-manager-type: aio
      longhorn.io/managed-by: longhorn-manager
      longhorn.io/node: zee8608workerapi02
    name: instance-manager-cebb946b3b3be3279c2f59f7e76f53b9
    namespace: longhorn-system
  timestamp: "2025-10-03T07:58:58Z"
  window: 19.606s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-liveness-probe
    usage:
      cpu: 552851n
      memory: 17400Ki
  - name: node-driver-registrar
    usage:
      cpu: 23184n
      memory: 8872Ki
  - name: longhorn-csi-plugin
    usage:
      cpu: 363199n
      memory: 23556Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: longhorn-csi-plugin
      controller-revision-hash: 5bf48968d4
      pod-template-generation: "2"
    name: longhorn-csi-plugin-6dcgc
    namespace: longhorn-system
  timestamp: "2025-10-03T07:59:01Z"
  window: 17.833s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: node-driver-registrar
    usage:
      cpu: 249980n
      memory: 9072Ki
  - name: longhorn-csi-plugin
    usage:
      cpu: 424893n
      memory: 23844Ki
  - name: longhorn-liveness-probe
    usage:
      cpu: 463143n
      memory: 15388Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: longhorn-csi-plugin
      controller-revision-hash: 5bf48968d4
      pod-template-generation: "2"
    name: longhorn-csi-plugin-shphp
    namespace: longhorn-system
  timestamp: "2025-10-03T07:58:42Z"
  window: 11.031s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-liveness-probe
    usage:
      cpu: 400715n
      memory: 18812Ki
  - name: node-driver-registrar
    usage:
      cpu: 19294n
      memory: 11560Ki
  - name: longhorn-csi-plugin
    usage:
      cpu: 247157n
      memory: 28648Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: longhorn-csi-plugin
      controller-revision-hash: 5bf48968d4
      pod-template-generation: "2"
    name: longhorn-csi-plugin-tswqt
    namespace: longhorn-system
  timestamp: "2025-10-03T07:58:51Z"
  window: 19.611s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-driver-deployer
    usage:
      cpu: 16703n
      memory: 22616Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: longhorn-driver-deployer
      app.kubernetes.io/instance: longhorn
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.8.0
      helm.sh/chart: longhorn-1.8.0
      pod-template-hash: 86695f796b
    name: longhorn-driver-deployer-86695f796b-gfpf5
    namespace: longhorn-system
  timestamp: "2025-10-03T07:59:05Z"
  window: 24.606s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-manager
    usage:
      cpu: 9130411n
      memory: 242644Ki
  - name: pre-pull-share-manager-image
    usage:
      cpu: "0"
      memory: 640Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: longhorn-manager
      app.kubernetes.io/instance: longhorn
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.8.0
      controller-revision-hash: 899d7b89b
      helm.sh/chart: longhorn-1.8.0
      longhorn.io/admission-webhook: longhorn-admission-webhook
      longhorn.io/conversion-webhook: longhorn-conversion-webhook
      longhorn.io/recovery-backend: longhorn-recovery-backend
      pod-template-generation: "1"
    name: longhorn-manager-4ckwk
    namespace: longhorn-system
  timestamp: "2025-10-03T07:59:05Z"
  window: 15.267s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: pre-pull-share-manager-image
    usage:
      cpu: "0"
      memory: 636Ki
  - name: longhorn-manager
    usage:
      cpu: 10927235n
      memory: 206272Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: longhorn-manager
      app.kubernetes.io/instance: longhorn
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.8.0
      controller-revision-hash: 899d7b89b
      helm.sh/chart: longhorn-1.8.0
      longhorn.io/admission-webhook: longhorn-admission-webhook
      longhorn.io/conversion-webhook: longhorn-conversion-webhook
      longhorn.io/recovery-backend: longhorn-recovery-backend
      pod-template-generation: "1"
    name: longhorn-manager-d8z27
    namespace: longhorn-system
  timestamp: "2025-10-03T07:58:36Z"
  window: 17.813s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-manager
    usage:
      cpu: 15088447n
      memory: 428612Ki
  - name: pre-pull-share-manager-image
    usage:
      cpu: "0"
      memory: 516Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: longhorn-manager
      app.kubernetes.io/instance: longhorn
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.8.0
      controller-revision-hash: 899d7b89b
      helm.sh/chart: longhorn-1.8.0
      longhorn.io/admission-webhook: longhorn-admission-webhook
      longhorn.io/conversion-webhook: longhorn-conversion-webhook
      longhorn.io/recovery-backend: longhorn-recovery-backend
      pod-template-generation: "1"
    name: longhorn-manager-pr755
    namespace: longhorn-system
  timestamp: "2025-10-03T07:58:57Z"
  window: 10.967s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-ui
    usage:
      cpu: "0"
      memory: 4132Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: longhorn-ui
      app.kubernetes.io/instance: longhorn
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.8.0
      helm.sh/chart: longhorn-1.8.0
      pod-template-hash: 5fbbcc8fb
    name: longhorn-ui-5fbbcc8fb-pmls9
    namespace: longhorn-system
  timestamp: "2025-10-03T07:58:59Z"
  window: 15.663s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-ui
    usage:
      cpu: "0"
      memory: 5880Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:16Z"
    labels:
      app: longhorn-ui
      app.kubernetes.io/instance: longhorn
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.8.0
      helm.sh/chart: longhorn-1.8.0
      pod-template-hash: 5fbbcc8fb
    name: longhorn-ui-5fbbcc8fb-vm9kl
    namespace: longhorn-system
  timestamp: "2025-10-03T07:59:01Z"
  window: 12.723s
kind: List
metadata:
  resourceVersion: ""
