apiVersion: v1
items:
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
      email: support@mongodb.com
      meta.helm.sh/release-name: community-operator
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2025-02-10T09:01:32Z"
    generation: 1
    labels:
      name: mongodb-kubernetes-operator
      pod-template-hash: 7b7b59cc5c
    name: mongodb-kubernetes-operator-7b7b59cc5c
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: mongodb-kubernetes-operator
      uid: be6d64ee-a283-4974-a6bb-ee1fef8198d7
    resourceVersion: "72238801"
    uid: 2ee30a8a-4784-4f5e-a810-22c666cd85a5
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: mongodb-kubernetes-operator
        pod-template-hash: 7b7b59cc5c
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: mongodb-kubernetes-operator
          pod-template-hash: 7b7b59cc5c
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - mongodb-kubernetes-operator
              topologyKey: kubernetes.io/hostname
        containers:
        - command:
          - /usr/local/bin/entrypoint
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: mongodb-kubernetes-operator
          - name: AGENT_IMAGE
            value: quay.io/mongodb/mongodb-agent-ubi:108.0.2.8729-1
          - name: VERSION_UPGRADE_HOOK_IMAGE
            value: quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.9
          - name: READINESS_PROBE_IMAGE
            value: quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.22
          - name: MONGODB_IMAGE
            value: mongodb-community-server
          - name: MONGODB_REPO_URL
            value: docker.io/mongodb
          - name: MDB_IMAGE_TYPE
            value: ubi8
          image: quay.io/mongodb/mongodb-kubernetes-operator:0.12.0
          imagePullPolicy: Always
          name: mongodb-kubernetes-operator
          resources:
            limits:
              cpu: 1100m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
          runAsUser: 2000
        serviceAccount: mongodb-kubernetes-operator
        serviceAccountName: mongodb-kubernetes-operator
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
kind: List
metadata:
  resourceVersion: ""
