apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2025-04-16T11:38:04Z"
    generateName: default-http-backend-5bf7597cb7-
    labels:
      app: kubesphere
      component: kubesphere-router
      pod-template-hash: 5bf7597cb7
    name: default-http-backend-5bf7597cb7-45crg
    namespace: kubesphere-controls-system
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: default-http-backend-5bf7597cb7
      uid: 3539d72e-9db2-4243-95fd-e40b9d5b4d33
    resourceVersion: "72238358"
    uid: 9d3f5a48-7ebe-48d3-aa25-fa8ec09450d2
  spec:
    containers:
    - image: mirrorgooglecontainers/defaultbackend-amd64:1.4
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      name: default-http-backend
      ports:
      - containerPort: 8080
        protocol: TCP
      resources:
        limits:
          cpu: 10m
          memory: 20Mi
        requests:
          cpu: 10m
          memory: 20Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-mtzlc
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: zee8608workerapi01
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 60
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-mtzlc
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-06-23T16:34:18Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-04-16T12:45:55Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-06-23T16:34:18Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-06-23T16:34:18Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-04-16T12:48:02Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://f39ef9d5911da73951e55cc911345e5276936d38f8f173b7ed5e926ef58021f8
      image: docker.io/mirrorgooglecontainers/defaultbackend-amd64:1.4
      imageID: docker.io/mirrorgooglecontainers/defaultbackend-amd64@sha256:05cb942c5ff93ebb6c63d48737cd39d4fa1c6fa9dc7a4d53b2709f5b3c8333e8
      lastState: {}
      name: default-http-backend
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2025-06-23T16:34:18Z"
    hostIP: 10.48.219.138
    hostIPs:
    - ip: 10.48.219.138
    phase: Running
    podIP: 192.168.5.205
    podIPs:
    - ip: 192.168.5.205
    qosClass: Guaranteed
    startTime: "2025-04-16T12:45:55Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2025-04-16T11:40:16Z"
    generateName: kubectl-admin-6bb69fcfdf-
    labels:
      kubesphere.io/username: admin
      pod-template-hash: 6bb69fcfdf
    name: kubectl-admin-6bb69fcfdf-zfndf
    namespace: kubesphere-controls-system
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: kubectl-admin-6bb69fcfdf
      uid: b03e6fb2-e5f4-4bad-9b3b-b73f7bf7ebc8
    resourceVersion: "70961486"
    uid: 8f62a4d7-52e2-48e8-a177-ec5c944f9e36
  spec:
    containers:
    - image: kubesphere/kubectl:v1.22.0
      imagePullPolicy: IfNotPresent
      name: kubectl
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /etc/localtime
        name: host-time
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-bnzq6
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: zee8608workerapi02
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: kubesphere-cluster-admin
    serviceAccountName: kubesphere-cluster-admin
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - hostPath:
        path: /etc/localtime
        type: ""
      name: host-time
    - name: kube-api-access-bnzq6
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-06-20T20:32:02Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-04-16T12:45:55Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-06-20T20:32:02Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-06-20T20:32:02Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-04-16T12:48:02Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://fa25d3c20b9125b98aa999ac37b1b1827bef69554529630f9289f5512c5a1e21
      image: docker.io/kubesphere/kubectl:v1.22.0
      imageID: docker.io/kubesphere/kubectl@sha256:32c554d9eaaf6c509d00244243f24b2cb32b8aa5ebb59ac44562629c372a16b8
      lastState:
        terminated:
          containerID: containerd://592b44de555b838bc02ca1245f561e5694bde823e498738db855f0f1306c0313
          exitCode: 255
          finishedAt: "2025-06-20T20:30:30Z"
          reason: Unknown
          startedAt: "2025-04-16T12:48:58Z"
      name: kubectl
      ready: true
      restartCount: 1
      started: true
      state:
        running:
          startedAt: "2025-06-20T20:32:01Z"
    hostIP: 10.48.219.139
    hostIPs:
    - ip: 10.48.219.139
    phase: Running
    podIP: 192.168.3.228
    podIPs:
    - ip: 192.168.3.228
    qosClass: BestEffort
    startTime: "2025-04-16T12:45:55Z"
kind: List
metadata:
  resourceVersion: ""
