apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubernetes.io/created-by: kubesphere.io/ks-router
      meta.helm.sh/release-name: ks-core
      meta.helm.sh/release-namespace: kubesphere-system
    creationTimestamp: "2025-02-10T06:58:20Z"
    labels:
      app: kubesphere
      app.kubernetes.io/managed-by: Helm
      component: kubesphere-router
    name: default-http-backend
    namespace: kubesphere-controls-system
    resourceVersion: "1021550"
    uid: 3df15f83-b3ed-47fc-8948-2bb8c4834559
  spec:
    clusterIP: 10.101.119.14
    clusterIPs:
    - 10.101.119.14
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: kubesphere
      component: kubesphere-router
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
