apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubernetes.io/created-by: kubesphere.io/ks-router
      meta.helm.sh/release-name: ks-core
      meta.helm.sh/release-namespace: kubesphere-system
    creationTimestamp: "2025-02-10T06:58:20Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    name: nginx-ingress-role-nisa-binding
    namespace: kubesphere-controls-system
    resourceVersion: "1021546"
    uid: 6b134bca-f5f7-4c84-be23-7e8a9296c93c
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: system:kubesphere-router-role
  subjects:
  - kind: ServiceAccount
    name: kubesphere-router-serviceaccount
    namespace: kubesphere-controls-system
kind: List
metadata:
  resourceVersion: ""
