apiVersion: v1
items:
- apiVersion: apps/v1
  data:
    spec:
      template:
        $patch: replace
        metadata:
          creationTimestamp: null
          labels:
            k8s-app: kube-proxy
        spec:
          containers:
          - command:
            - /usr/local/bin/kube-proxy
            - --config=/var/lib/kube-proxy/config.conf
            - --hostname-override=$(NODE_NAME)
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            image: registry.k8s.io/kube-proxy:v1.30.9
            imagePullPolicy: IfNotPresent
            name: kube-proxy
            resources: {}
            securityContext:
              privileged: true
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/lib/kube-proxy
              name: kube-proxy
            - mountPath: /run/xtables.lock
              name: xtables-lock
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
          dnsPolicy: ClusterFirst
          hostNetwork: true
          nodeSelector:
            kubernetes.io/os: linux
          priorityClassName: system-node-critical
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: kube-proxy
          serviceAccountName: kube-proxy
          terminationGracePeriodSeconds: 30
          tolerations:
          - operator: Exists
          volumes:
          - configMap:
              defaultMode: 420
              name: kube-proxy
            name: kube-proxy
          - hostPath:
              path: /run/xtables.lock
              type: FileOrCreate
            name: xtables-lock
          - hostPath:
              path: /lib/modules
              type: ""
            name: lib-modules
  kind: ControllerRevision
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "1"
    creationTimestamp: "2025-02-07T07:59:29Z"
    labels:
      controller-revision-hash: 79c94c5cb4
      k8s-app: kube-proxy
    name: kube-proxy-79c94c5cb4
    namespace: kube-system
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: DaemonSet
      name: kube-proxy
      uid: 27c3a05f-34c7-4b31-afaa-6a1d52f7b481
    resourceVersion: "337"
    uid: 7b17fdcd-f479-452f-8c30-4c834c9d2626
  revision: 1
- apiVersion: apps/v1
  data:
    spec:
      template:
        $patch: replace
        metadata:
          creationTimestamp: null
          labels:
            app: snapshot-controller
        spec:
          containers:
          - args:
            - --v=5
            - --leader-election=false
            image: csiplugin/snapshot-controller:v4.0.0
            imagePullPolicy: IfNotPresent
            name: snapshot-controller
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: snapshot-controller
          serviceAccountName: snapshot-controller
          terminationGracePeriodSeconds: 30
  kind: ControllerRevision
  metadata:
    annotations:
      meta.helm.sh/release-name: snapshot-controller
      meta.helm.sh/release-namespace: kube-system
    creationTimestamp: "2025-02-10T06:55:59Z"
    labels:
      app: snapshot-controller
      controller.kubernetes.io/hash: 7d87fc7c78
    name: snapshot-controller-7d87fc7c78
    namespace: kube-system
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: StatefulSet
      name: snapshot-controller
      uid: a5bcb0f8-f08b-455e-a8b6-857b22fa5155
    resourceVersion: "1020808"
    uid: 2b6508ab-5fdf-4d2e-9ae7-858184260bdc
  revision: 1
kind: List
metadata:
  resourceVersion: ""
