apiVersion: v1
items:
- apiVersion: coordination.k8s.io/v1
  kind: Lease
  metadata:
    creationTimestamp: "2025-02-07T08:04:09Z"
    labels:
      apiserver.kubernetes.io/identity: kube-apiserver
      kubernetes.io/hostname: zee8608masterapi03
    name: apiserver-bscz6ooufkackv7phfdra7rxp4
    namespace: kube-system
    resourceVersion: "122980047"
    uid: 9647a544-9ecd-4868-80dd-c9139557b151
  spec:
    holderIdentity: apiserver-bscz6ooufkackv7phfdra7rxp4_4c4a2f12-c4fa-4693-8c34-9361f057fd34
    leaseDurationSeconds: 3600
    renewTime: "2025-10-03T07:57:55.349071Z"
- apiVersion: coordination.k8s.io/v1
  kind: Lease
  metadata:
    creationTimestamp: "2025-02-07T08:02:27Z"
    labels:
      apiserver.kubernetes.io/identity: kube-apiserver
      kubernetes.io/hostname: zee8608masterapi02
    name: apiserver-kxndkjpotv2ppannchvbkuclpy
    namespace: kube-system
    resourceVersion: "122980061"
    uid: 33b5702a-6ce1-4dd5-b696-514768b87b29
  spec:
    holderIdentity: apiserver-kxndkjpotv2ppannchvbkuclpy_5f4a4ee7-b2d1-4c07-a1e6-6dad1a9ef2cb
    leaseDurationSeconds: 3600
    renewTime: "2025-10-03T07:58:18.596269Z"
- apiVersion: coordination.k8s.io/v1
  kind: Lease
  metadata:
    creationTimestamp: "2025-02-07T07:59:13Z"
    labels:
      apiserver.kubernetes.io/identity: kube-apiserver
      kubernetes.io/hostname: zee8608masterapi01
    name: apiserver-tljm23v7iwqlhqqle7mqajd2xa
    namespace: kube-system
    resourceVersion: "122980082"
    uid: d1906656-039b-4cd6-b0ad-c1b4808767bf
  spec:
    holderIdentity: apiserver-tljm23v7iwqlhqqle7mqajd2xa_f1e3d5b8-ef4a-4e5b-8112-5a05e706a3ab
    leaseDurationSeconds: 3600
    renewTime: "2025-10-03T07:59:04.695086Z"
- apiVersion: coordination.k8s.io/v1
  kind: Lease
  metadata:
    creationTimestamp: "2025-02-08T18:54:56Z"
    name: cert-manager-cainjector-leader-election
    namespace: kube-system
    resourceVersion: "122980012"
    uid: 32d2e71c-baad-41f0-a212-3f319f2ba92a
  spec:
    acquireTime: "2025-06-23T16:35:59.266322Z"
    holderIdentity: cert-manager-cainjector-67ff4bc9cd-zlxr5_84391365-742f-4d4d-ba14-65ea23ca4609
    leaseDurationSeconds: 60
    leaseTransitions: 4
    renewTime: "2025-10-03T07:57:59.989432Z"
- apiVersion: coordination.k8s.io/v1
  kind: Lease
  metadata:
    creationTimestamp: "2025-02-08T18:54:54Z"
    name: cert-manager-controller
    namespace: kube-system
    resourceVersion: "122980021"
    uid: 8e3f035b-050e-4576-a4ba-6a2521b5fe81
  spec:
    acquireTime: "2025-04-16T13:06:48.855641Z"
    holderIdentity: cert-manager-97f647775-wxbkc-external-cert-manager-controller
    leaseDurationSeconds: 60
    leaseTransitions: 1
    renewTime: "2025-10-03T07:58:04.783737Z"
- apiVersion: coordination.k8s.io/v1
  kind: Lease
  metadata:
    creationTimestamp: "2025-02-07T07:59:14Z"
    name: kube-controller-manager
    namespace: kube-system
    resourceVersion: "122980096"
    uid: c36263b9-27c3-4b9e-bf40-4a8d3821c934
  spec:
    acquireTime: "2025-06-20T20:21:45.842321Z"
    holderIdentity: zee8608masterapi01_c745bece-a22a-49da-b709-011516e61557
    leaseDurationSeconds: 15
    leaseTransitions: 11
    renewTime: "2025-10-03T07:59:07.951766Z"
- apiVersion: coordination.k8s.io/v1
  kind: Lease
  metadata:
    creationTimestamp: "2025-02-07T07:59:17Z"
    name: kube-scheduler
    namespace: kube-system
    resourceVersion: "122980095"
    uid: 1479610e-b686-4a45-8c1a-daccc2ae0fc0
  spec:
    acquireTime: "2025-06-20T20:21:47.593990Z"
    holderIdentity: zee8608masterapi01_86c9449a-8a22-4fa8-b382-5cbed8127948
    leaseDurationSeconds: 15
    leaseTransitions: 12
    renewTime: "2025-10-03T07:59:07.948902Z"
kind: List
metadata:
  resourceVersion: ""
