apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      meta.helm.sh/release-name: snapshot-controller
      meta.helm.sh/release-namespace: kube-system
    creationTimestamp: "2025-02-10T06:55:57Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
    name: snapshot-controller
    namespace: kube-system
    resourceVersion: "70961420"
    uid: a5bcb0f8-f08b-455e-a8b6-857b22fa5155
  spec:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: snapshot-controller
    serviceName: snapshot-controller
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: snapshot-controller
      spec:
        containers:
        - args:
          - --v=5
          - --leader-election=false
          image: csiplugin/snapshot-controller:v4.0.0
          imagePullPolicy: IfNotPresent
          name: snapshot-controller
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: snapshot-controller
        serviceAccountName: snapshot-controller
        terminationGracePeriodSeconds: 30
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
  status:
    availableReplicas: 1
    collisionCount: 0
    currentReplicas: 1
    currentRevision: snapshot-controller-7d87fc7c78
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updateRevision: snapshot-controller-7d87fc7c78
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
