apiVersion: v1
items:
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-flannel
    usage:
      cpu: 7384535n
      memory: 13188Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:57:54Z"
    labels:
      app: flannel
      controller-revision-hash: 6d455c8676
      pod-template-generation: "1"
      tier: node
    name: kube-flannel-ds-6nbks
    namespace: kube-flannel
  timestamp: "2025-10-03T07:58:30Z"
  window: 31.906s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-flannel
    usage:
      cpu: 6418461n
      memory: 12148Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:57:54Z"
    labels:
      app: flannel
      controller-revision-hash: 6d455c8676
      pod-template-generation: "1"
      tier: node
    name: kube-flannel-ds-892lj
    namespace: kube-flannel
  timestamp: "2025-10-03T07:57:17Z"
  window: 11.516s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-flannel
    usage:
      cpu: 8043719n
      memory: 27984Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:57:54Z"
    labels:
      app: flannel
      controller-revision-hash: 6d455c8676
      pod-template-generation: "1"
      tier: node
    name: kube-flannel-ds-cr6sd
    namespace: kube-flannel
  timestamp: "2025-10-03T07:57:25Z"
  window: 18.916s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-flannel
    usage:
      cpu: 8165511n
      memory: 19076Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:57:54Z"
    labels:
      app: flannel
      controller-revision-hash: 6d455c8676
      pod-template-generation: "1"
      tier: node
    name: kube-flannel-ds-dvsbd
    namespace: kube-flannel
  timestamp: "2025-10-03T07:57:21Z"
  window: 19.328s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-flannel
    usage:
      cpu: 7140315n
      memory: 17876Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:57:54Z"
    labels:
      app: flannel
      controller-revision-hash: 6d455c8676
      pod-template-generation: "1"
      tier: node
    name: kube-flannel-ds-h9rrs
    namespace: kube-flannel
  timestamp: "2025-10-03T07:57:29Z"
  window: 12.308s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-flannel
    usage:
      cpu: 6691760n
      memory: 12368Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:57:54Z"
    labels:
      app: flannel
      controller-revision-hash: 6d455c8676
      pod-template-generation: "1"
      tier: node
    name: kube-flannel-ds-nmx5p
    namespace: kube-flannel
  timestamp: "2025-10-03T07:57:34Z"
  window: 14.625s
kind: List
metadata:
  resourceVersion: ""
