apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIBGpEgb8zVRswDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNTAyMDcwNzU0MDZaFw0zNTAyMDUwNzU5MDZaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQDcKXkUtHMKM7qeci7OlLNez2FlydMAt9l6KKkywvtuLyaMIrJKbFPh8hml
      H2dnMm7PRXcy/xoZFucFHfjaUY+euYJ6cf3MAoQfG/SfgpA5TRqEPbdxwc+GHDy7
      6ZoH9gIYHLkdeRUw0QTKKZTNYmRhRZ7oLjRmssL0kSpWOrg3EdN/K95ZT4eczUrl
      ts/rLLJPILP6LuWGllkIqnKBpm95RbpeGfTCoCAYbYIpbm0XzbybHeJuar+mA2kG
      Vhv8LJH9HIUCPTPLY4eUNFM5yAOlqR4p2tKpIHcaQC8WZhJqQBd3/OLx1fDnEsu5
      KCg99V39QHNmXONGKNdVZdnvCa8DAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRSbsFhjuaavB3D2AJAgY6/Kg93NDAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQBtFumnVigF
      ZqgHe3ok8jdx/o48sBfKM+N+eiqEKsuVuWhiYcMGhlXqqvgX5qHDcM+QPC2x4QxE
      NiZ0beIXwVs/xeOx9KeoPfnem58Ke51qlCBiTZrPTFhCIGUfqpD9SAxFRXX/4Re+
      ff8hORHxXHM+mo9fRUIsDkEON3IoFbImuq0bfklHbPfFJ1z+f/Fg+3bG4bUcMRDG
      /N3BorYqcnQxsvXlZpw3yDQrm3VukCTZSKm3FAuakJlBntmxHM4UewnN0VaF8ZAR
      dfz/NBVYyrEu/zPNPOYYHVLLfcMPbtlxnCnQuBB5C6Bv0hH1YNcwvEObxZH4+8G0
      O6YN95NGdZMw
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2025-02-10T11:50:13Z"
    name: kube-root-ca.crt
    namespace: rbmq
    resourceVersion: "1125349"
    uid: 653d45e9-b332-49cd-b8ad-3030f89ec56d
- apiVersion: v1
  data:
    enabled_plugins: '[rabbitmq_peer_discovery_k8s,rabbitmq_prometheus,rabbitmq_management].'
  kind: ConfigMap
  metadata:
    creationTimestamp: "2025-02-21T15:48:54Z"
    labels:
      app.kubernetes.io/component: rabbitmq
      app.kubernetes.io/name: rabbitmq-cluster
      app.kubernetes.io/part-of: rabbitmq
    name: rabbitmq-cluster-plugins-conf
    namespace: rbmq
    ownerReferences:
    - apiVersion: rabbitmq.com/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: RabbitmqCluster
      name: rabbitmq-cluster
      uid: df0e84b3-643d-42c7-960a-e7f9daca5421
    resourceVersion: "6107609"
    uid: c997283b-b327-40af-a644-3735b94dc9ac
- apiVersion: v1
  data:
    operatorDefaults.conf: |
      queue_master_locator                       = min-masters
      disk_free_limit.absolute                   = 2GB
      cluster_partition_handling                 = pause_minority
      cluster_formation.peer_discovery_backend   = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host                 = kubernetes.default
      cluster_formation.k8s.address_type         = hostname
      cluster_formation.target_cluster_size_hint = 3
      cluster_name                               = rabbitmq-cluster
      auth_mechanisms.1                          = PLAIN
      auth_mechanisms.2                          = AMQPLAIN
    userDefinedConfiguration.conf: |
      total_memory_available_override_value = 1717986919
  kind: ConfigMap
  metadata:
    creationTimestamp: "2025-02-21T15:48:54Z"
    labels:
      app.kubernetes.io/component: rabbitmq
      app.kubernetes.io/name: rabbitmq-cluster
      app.kubernetes.io/part-of: rabbitmq
    name: rabbitmq-cluster-server-conf
    namespace: rbmq
    ownerReferences:
    - apiVersion: rabbitmq.com/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: RabbitmqCluster
      name: rabbitmq-cluster
      uid: df0e84b3-643d-42c7-960a-e7f9daca5421
    resourceVersion: "6107612"
    uid: e259cf68-e271-438a-a5d9-9c7ed1e25068
kind: List
metadata:
  resourceVersion: ""
