apiVersion: v1
items:
- apiVersion: installer.kubesphere.io/v1alpha1
  kind: ClusterConfiguration
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"installer.kubesphere.io/v1alpha1","kind":"ClusterConfiguration","metadata":{"annotations":{},"labels":{"version":"v3.4.1"},"name":"ks-installer","namespace":"kubesphere-system"},"spec":{"alerting":{"enabled":true},"auditing":{"enabled":true},"authentication":{"jwtSecret":""},"common":{"core":{"console":{"enableMultiLogin":true,"port":30880,"type":"NodePort"}},"es":{"basicAuth":{"enabled":false,"password":"","username":""},"elkPrefix":"logstash","enabled":false,"externalElasticsearchHost":"","externalElasticsearchPort":"","logMaxAge":7},"gpu":{"kinds":[{"default":true,"resourceName":"nvidia.com/gpu","resourceType":"GPU"}]},"minio":{"volumeSize":"20Gi"},"monitoring":{"GPUMonitoring":{"enabled":false},"endpoint":"http://prometheus-operated.kubesphere-monitoring-system.svc:9090"},"openldap":{"enabled":false,"volumeSize":"2Gi"},"opensearch":{"basicAuth":{"enabled":true,"password":"admin","username":"admin"},"dashboard":{"enabled":false},"enabled":true,"externalOpensearchHost":"","externalOpensearchPort":"","logMaxAge":7,"opensearchPrefix":"whizard"},"redis":{"enableHA":false,"enabled":false,"volumeSize":"2Gi"}},"devops":{"enabled":false,"jenkinsCpuLim":1,"jenkinsCpuReq":0.5,"jenkinsMemoryLim":"4Gi","jenkinsMemoryReq":"4Gi","jenkinsVolumeSize":"16Gi"},"edgeruntime":{"enabled":false,"kubeedge":{"cloudCore":{"cloudHub":{"advertiseAddress":[""]},"service":{"cloudhubHttpsNodePort":"30002","cloudhubNodePort":"30000","cloudhubQuicNodePort":"30001","cloudstreamNodePort":"30003","tunnelNodePort":"30004"}},"enabled":false,"iptables-manager":{"enabled":true,"mode":"external"}}},"etcd":{"endpointIps":"localhost","monitoring":false,"port":2379,"tlsEnable":true},"events":{"enabled":false,"ruler":{"enabled":true,"replicas":2}},"gatekeeper":{"enabled":false},"local_registry":"","logging":{"enabled":false,"logsidecar":{"enabled":true,"replicas":2}},"metrics_server":{"enabled":false},"monitoring":{"gpu":{"nvidia_dcgm_exporter":{"enabled":false}},"node_exporter":{"port":9100},"storageClass":""},"multicluster":{"clusterRole":"none"},"network":{"ippool":{"type":"none"},"networkpolicy":{"enabled":false},"topology":{"type":"none"}},"openpitrix":{"store":{"enabled":false}},"persistence":{"storageClass":""},"servicemesh":{"enabled":false,"istio":{"components":{"cni":{"enabled":false},"ingressGateways":[{"enabled":false,"name":"istio-ingressgateway"}]}}},"terminal":{"timeout":600}}}
    creationTimestamp: "2025-02-10T06:55:11Z"
    generation: 18
    labels:
      version: v3.4.1
    name: ks-installer
    namespace: kubesphere-system
    resourceVersion: "70973179"
    uid: 2792df1a-6998-4399-86ac-08d3cf2a1970
  spec:
    alerting:
      enabled: true
    auditing:
      enabled: true
    authentication:
      jwtSecret: ""
    common:
      core:
        console:
          enableMultiLogin: true
          port: 30880
          type: NodePort
      es:
        basicAuth:
          enabled: false
          password: ""
          username: ""
        elkPrefix: logstash
        enabled: false
        externalElasticsearchHost: ""
        externalElasticsearchPort: ""
        logMaxAge: 7
      gpu:
        kinds:
        - default: true
          resourceName: nvidia.com/gpu
          resourceType: GPU
      minio:
        volumeSize: 20Gi
      monitoring:
        GPUMonitoring:
          enabled: false
        endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      openldap:
        enabled: false
        volumeSize: 2Gi
      opensearch:
        basicAuth:
          enabled: true
          password: admin
          username: admin
        dashboard:
          enabled: false
        enabled: true
        externalOpensearchHost: ""
        externalOpensearchPort: ""
        logMaxAge: 7
        opensearchPrefix: whizard
      redis:
        enableHA: false
        enabled: false
        volumeSize: 2Gi
    devops:
      enabled: false
      jenkinsCpuLim: 1
      jenkinsCpuReq: 0.5
      jenkinsMemoryLim: 4Gi
      jenkinsMemoryReq: 4Gi
      jenkinsVolumeSize: 16Gi
    edgeruntime:
      enabled: false
      kubeedge:
        cloudCore:
          cloudHub:
            advertiseAddress:
            - ""
          service:
            cloudhubHttpsNodePort: "30002"
            cloudhubNodePort: "30000"
            cloudhubQuicNodePort: "30001"
            cloudstreamNodePort: "30003"
            tunnelNodePort: "30004"
        enabled: false
        iptables-manager:
          enabled: true
          mode: external
    etcd:
      endpointIps: localhost
      monitoring: false
      port: 2379
      tlsEnable: true
    events:
      enabled: false
      ruler:
        enabled: true
        replicas: 2
    gatekeeper:
      enabled: false
    local_registry: ""
    logging:
      enabled: false
      logsidecar:
        enabled: true
        replicas: 2
    metrics_server:
      enabled: false
    monitoring:
      gpu:
        nvidia_dcgm_exporter:
          enabled: false
      node_exporter:
        port: 9100
      storageClass: ""
    multicluster:
      clusterRole: none
    network:
      ippool:
        type: none
      networkpolicy:
        enabled: false
      topology:
        type: none
    openpitrix:
      store:
        enabled: false
    persistence:
      storageClass: ""
    servicemesh:
      enabled: false
      istio:
        components:
          cni:
            enabled: false
          ingressGateways:
          - enabled: false
            name: istio-ingressgateway
    terminal:
      timeout: 600
  status:
    alerting:
      enabledTime: 2025-03-04T14:16:34IST
      status: enabled
    auditing:
      enabledTime: 2025-03-04T14:14:45IST
      status: enabled
    clusterId: fa54a9c8-daa0-46af-963b-36b7eaac63bb-1739171099
    core:
      enabledTime: 2025-06-21T02:41:53IST
      status: enabled
      version: v3.4.1
    fluentbit:
      enabledTime: 2025-03-04T14:11:22IST
      status: enabled
    monitoring:
      enabledTime: 2025-06-21T02:43:35IST
      status: enabled
    opensearch:
      enabledTime: 2025-03-04T14:11:08IST
      status: enabled
kind: List
metadata:
  resourceVersion: ""
