apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 192.168.3.237
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: zee8608workerapi02
    targetRef:
      kind: Pod
      name: ks-apiserver-945bb6c8c-dr2pf
      namespace: kubesphere-system
      uid: dad2c469-d2d2-4c88-a311-775b111bb67e
  kind: EndpointSlice
  metadata:
    creationTimestamp: "2025-02-10T06:58:22Z"
    generateName: ks-apiserver-
    generation: 20
    labels:
      app: ks-apiserver
      app.kubernetes.io/managed-by: Helm
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: ks-apiserver
      tier: backend
      version: v3.3.2
    name: ks-apiserver-2znp8
    namespace: kubesphere-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: ks-apiserver
      uid: 650f4883-5ca5-44ac-96b9-0b0638f35ac7
    resourceVersion: "70961415"
    uid: e0cda35a-95de-48c6-9b09-e6e9b88492f7
  ports:
  - name: ""
    port: 9090
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 192.168.3.236
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: zee8608workerapi02
    targetRef:
      kind: Pod
      name: ks-console-7bcbf87f4-snqbp
      namespace: kubesphere-system
      uid: 197d7834-7e85-4516-bc2b-7c0213e9697d
  kind: EndpointSlice
  metadata:
    creationTimestamp: "2025-02-10T06:58:22Z"
    generateName: ks-console-
    generation: 20
    labels:
      app: ks-console
      app.kubernetes.io/managed-by: Helm
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: ks-console
      tier: frontend
      version: v3.3.2
    name: ks-console-gsk6m
    namespace: kubesphere-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: ks-console
      uid: 0b791a77-5748-4a03-9d29-f6bec6c4ca18
    resourceVersion: "70961427"
    uid: 53522845-0856-432c-8f37-c2b73d5b9712
  ports:
  - name: nginx
    port: 8000
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 192.168.3.238
    conditions:
      ready: false
      serving: false
      terminating: false
    nodeName: zee8608workerapi02
    targetRef:
      kind: Pod
      name: ks-controller-manager-6c9757d557-wqqf2
      namespace: kubesphere-system
      uid: 7db78378-22bf-40ae-a316-2436099dc10f
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-07-31T01:22:39Z"
    creationTimestamp: "2025-02-10T06:58:21Z"
    generateName: ks-controller-manager-
    generation: 45
    labels:
      app: ks-controller-manager
      app.kubernetes.io/managed-by: Helm
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: ks-controller-manager
      tier: backend
      version: v3.3.2
    name: ks-controller-manager-c4bbk
    namespace: kubesphere-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: ks-controller-manager
      uid: 87c7ad77-9e60-4f76-82ba-5cc544f60945
    resourceVersion: "91798988"
    uid: f8034c50-a7d5-4c2f-a2cc-154912c137b7
  ports:
  - name: ""
    port: 8443
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
