apiVersion: v1
items:
- apiVersion: coordination.k8s.io/v1
  kind: Lease
  metadata:
    creationTimestamp: "2025-02-10T07:04:42Z"
    name: ks-controller-manager-leader-election
    namespace: kubesphere-system
    resourceVersion: "91798802"
    uid: 1fb0f988-1f07-49ae-8f99-4a0a5cf7feaa
  spec:
    acquireTime: "2025-07-03T00:45:15.487548Z"
    holderIdentity: ks-controller-manager-6c9757d557-wqqf2_798e6253-d6a6-46f9-9b2f-b2a37ca48714
    leaseDurationSeconds: 30
    leaseTransitions: 14
    renewTime: "2025-07-31T01:22:18.744749Z"
kind: List
metadata:
  resourceVersion: ""
