apiVersion: v1
items:
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: ks-apiserver
    usage:
      cpu: 927931n
      memory: 114704Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:06Z"
    labels:
      app: ks-apiserver
      pod-template-hash: 945bb6c8c
      tier: backend
    name: ks-apiserver-945bb6c8c-dr2pf
    namespace: kubesphere-system
  timestamp: "2025-10-03T07:58:46Z"
  window: 19.301s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: ks-console
    usage:
      cpu: 26163n
      memory: 69056Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:06Z"
    labels:
      app: ks-console
      pod-template-hash: 7bcbf87f4
      tier: frontend
    name: ks-console-7bcbf87f4-snqbp
    namespace: kubesphere-system
  timestamp: "2025-10-03T07:58:46Z"
  window: 11.772s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: installer
    usage:
      cpu: 123788n
      memory: 83636Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2025-10-03T07:59:06Z"
    labels:
      app: ks-installer
      pod-template-hash: "6647685479"
    name: ks-installer-6647685479-6gs9f
    namespace: kubesphere-system
  timestamp: "2025-10-03T07:58:35Z"
  window: 15.583s
kind: List
metadata:
  resourceVersion: ""
