apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"alert-router","app.kubernetes.io/instance":"main","app.kubernetes.io/name":"alertmanager","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"0.23.0"},"name":"alertmanager-main","namespace":"kubesphere-monitoring-system"},"spec":{"ports":[{"name":"web","port":9093,"targetPort":"web"},{"name":"reloader-web","port":8080,"targetPort":"reloader-web"}],"selector":{"app.kubernetes.io/component":"alert-router","app.kubernetes.io/instance":"main","app.kubernetes.io/name":"alertmanager","app.kubernetes.io/part-of":"kube-prometheus"},"sessionAffinity":"ClientIP"}}
    creationTimestamp: "2025-02-10T07:02:21Z"
    labels:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/instance: main
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.23.0
    name: alertmanager-main
    namespace: kubesphere-monitoring-system
    resourceVersion: "1023108"
    uid: 43426217-3fa6-4f98-a788-786df9b9c4c1
  spec:
    clusterIP: 10.104.26.252
    clusterIPs:
    - 10.104.26.252
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: web
      port: 9093
      protocol: TCP
      targetPort: web
    - name: reloader-web
      port: 8080
      protocol: TCP
      targetPort: reloader-web
    selector:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/instance: main
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
    sessionAffinity: ClientIP
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-02-10T07:02:22Z"
    labels:
      operated-alertmanager: "true"
    name: alertmanager-operated
    namespace: kubesphere-monitoring-system
    ownerReferences:
    - apiVersion: monitoring.coreos.com/v1
      kind: Alertmanager
      name: main
      uid: b311a43b-db4f-4b42-ac99-8cdd545f6c12
    resourceVersion: "1023100"
    uid: 993b1614-5c24-4b14-a208-df197fe33059
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: web
      port: 9093
      protocol: TCP
      targetPort: web
    - name: tcp-mesh
      port: 9094
      protocol: TCP
      targetPort: 9094
    - name: udp-mesh
      port: 9094
      protocol: UDP
      targetPort: 9094
    selector:
      app.kubernetes.io/name: alertmanager
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"exporter","app.kubernetes.io/name":"kube-state-metrics","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"2.6.0"},"name":"kube-state-metrics","namespace":"kubesphere-monitoring-system"},"spec":{"clusterIP":"None","ports":[{"name":"https-main","port":8443,"targetPort":"https-main"},{"name":"https-self","port":9443,"targetPort":"https-self"}],"selector":{"app.kubernetes.io/component":"exporter","app.kubernetes.io/name":"kube-state-metrics","app.kubernetes.io/part-of":"kube-prometheus"}}}
    creationTimestamp: "2025-02-10T07:02:11Z"
    labels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.6.0
    name: kube-state-metrics
    namespace: kubesphere-monitoring-system
    resourceVersion: "1022882"
    uid: 4a8029f6-2a86-4a8c-96f9-8c0c0db69a4e
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https-main
      port: 8443
      protocol: TCP
      targetPort: https-main
    - name: https-self
      port: 9443
      protocol: TCP
      targetPort: https-self
    selector:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/part-of: kube-prometheus
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"exporter","app.kubernetes.io/name":"node-exporter","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"1.3.1"},"name":"node-exporter","namespace":"kubesphere-monitoring-system"},"spec":{"clusterIP":"None","ports":[{"name":"https","port":9100,"targetPort":"https"}],"selector":{"app.kubernetes.io/component":"exporter","app.kubernetes.io/name":"node-exporter","app.kubernetes.io/part-of":"kube-prometheus"}}}
    creationTimestamp: "2025-02-10T07:02:09Z"
    labels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 1.3.1
    name: node-exporter
    namespace: kubesphere-monitoring-system
    resourceVersion: "1022818"
    uid: ffee2cb2-61c2-4930-8e3a-a7625c4dd4da
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 9100
      protocol: TCP
      targetPort: https
    selector:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
      app.kubernetes.io/part-of: kube-prometheus
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: notification-manager
      meta.helm.sh/release-namespace: kubesphere-monitoring-system
    creationTimestamp: "2025-02-10T07:03:07Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      control-plane: controller-manager
    name: notification-manager-controller-metrics
    namespace: kubesphere-monitoring-system
    resourceVersion: "1023658"
    uid: 628e79a5-b415-4200-af71-ed8e9603b9c3
  spec:
    clusterIP: 10.109.173.233
    clusterIPs:
    - 10.109.173.233
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
    selector:
      control-plane: controller-manager
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-02-10T07:03:20Z"
    labels:
      app: notification-manager
      notification-manager: notification-manager
    name: notification-manager-svc
    namespace: kubesphere-monitoring-system
    ownerReferences:
    - apiVersion: notification.kubesphere.io/v2beta2
      blockOwnerDeletion: true
      controller: true
      kind: NotificationManager
      name: notification-manager
      uid: f4575e81-77a7-4b10-886d-cbafa8f4f240
    resourceVersion: "1023815"
    uid: d0c76878-4b7d-49d6-97a8-477385634015
  spec:
    clusterIP: 10.105.4.168
    clusterIPs:
    - 10.105.4.168
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: webhook
      port: 19093
      protocol: TCP
      targetPort: webhook
    selector:
      app: notification-manager
      notification-manager: notification-manager
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: notification-manager
      meta.helm.sh/release-namespace: kubesphere-monitoring-system
    creationTimestamp: "2025-02-10T07:03:07Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    name: notification-manager-webhook
    namespace: kubesphere-monitoring-system
    resourceVersion: "1023662"
    uid: 94d68206-6f90-4aa5-bfcc-5d96872e9cfd
  spec:
    clusterIP: 10.104.32.238
    clusterIPs:
    - 10.104.32.238
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
    selector:
      control-plane: controller-manager
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"prometheus","app.kubernetes.io/instance":"k8s","app.kubernetes.io/name":"prometheus","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"2.39.1"},"name":"prometheus-k8s","namespace":"kubesphere-monitoring-system"},"spec":{"ports":[{"name":"web","port":9090,"targetPort":"web"},{"name":"reloader-web","port":8080,"targetPort":"reloader-web"}],"selector":{"app.kubernetes.io/component":"prometheus","app.kubernetes.io/instance":"k8s","app.kubernetes.io/name":"prometheus","app.kubernetes.io/part-of":"kube-prometheus"},"sessionAffinity":"ClientIP"}}
    creationTimestamp: "2025-02-10T07:02:15Z"
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.39.1
    name: prometheus-k8s
    namespace: kubesphere-monitoring-system
    resourceVersion: "1022936"
    uid: b8037474-9ddc-4cb6-8645-122f3b2c3806
  spec:
    clusterIP: 10.96.119.173
    clusterIPs:
    - 10.96.119.173
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
    - name: reloader-web
      port: 8080
      protocol: TCP
      targetPort: reloader-web
    selector:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
    sessionAffinity: ClientIP
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-02-10T07:02:14Z"
    labels:
      operated-prometheus: "true"
    name: prometheus-operated
    namespace: kubesphere-monitoring-system
    ownerReferences:
    - apiVersion: monitoring.coreos.com/v1
      kind: Prometheus
      name: k8s
      uid: 4b040f98-bedd-48d7-8312-46382d0fa134
    resourceVersion: "1022931"
    uid: bb4b9498-f3fc-4d2e-b738-d16f1e61a0be
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
    selector:
      app.kubernetes.io/name: prometheus
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/name":"prometheus-operator","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"0.55.1"},"name":"prometheus-operator","namespace":"kubesphere-monitoring-system"},"spec":{"clusterIP":"None","ports":[{"name":"https","port":8443,"targetPort":"https"}],"selector":{"app.kubernetes.io/component":"controller","app.kubernetes.io/name":"prometheus-operator","app.kubernetes.io/part-of":"kube-prometheus"}}}
    creationTimestamp: "2025-02-10T07:01:55Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.55.1
    name: prometheus-operator
    namespace: kubesphere-monitoring-system
    resourceVersion: "1022712"
    uid: 70a8a7a3-c1d3-40e6-a74c-ec15174c0434
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
    selector:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"thanos-ruler","app.kubernetes.io/instance":"kubesphere","app.kubernetes.io/name":"thanos-ruler","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"0.31.0"},"name":"thanos-ruler-kubesphere","namespace":"kubesphere-monitoring-system"},"spec":{"ports":[{"name":"web","port":10902,"targetPort":"web"}],"selector":{"app.kubernetes.io/component":"thanos-ruler","app.kubernetes.io/instance":"kubesphere","app.kubernetes.io/name":"thanos-ruler","app.kubernetes.io/part-of":"kube-prometheus"},"sessionAffinity":"ClientIP"}}
    creationTimestamp: "2025-03-04T08:46:03Z"
    labels:
      app.kubernetes.io/component: thanos-ruler
      app.kubernetes.io/instance: kubesphere
      app.kubernetes.io/name: thanos-ruler
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.31.0
    name: thanos-ruler-kubesphere
    namespace: kubesphere-monitoring-system
    resourceVersion: "11877364"
    uid: 68fb1e66-1e37-4905-992b-ddc46a9d93a8
  spec:
    clusterIP: 10.111.100.90
    clusterIPs:
    - 10.111.100.90
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: web
      port: 10902
      protocol: TCP
      targetPort: web
    selector:
      app.kubernetes.io/component: thanos-ruler
      app.kubernetes.io/instance: kubesphere
      app.kubernetes.io/name: thanos-ruler
      app.kubernetes.io/part-of: kube-prometheus
    sessionAffinity: ClientIP
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-03-04T08:46:14Z"
    labels:
      operated-thanos-ruler: "true"
    name: thanos-ruler-operated
    namespace: kubesphere-monitoring-system
    ownerReferences:
    - apiVersion: monitoring.coreos.com/v1
      kind: ThanosRuler
      name: kubesphere
      uid: 8f59f3d8-07d7-4bef-a0a9-b0522abba605
    resourceVersion: "11877374"
    uid: 43c8a8aa-f039-42d0-a1cc-69b4b192c3af
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: web
      port: 10902
      protocol: TCP
      targetPort: web
    - name: grpc
      port: 10901
      protocol: TCP
      targetPort: grpc
    selector:
      app.kubernetes.io/name: thanos-ruler
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
