apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-06-23T16:34:21Z"
    creationTimestamp: "2025-02-10T07:02:23Z"
    labels:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/instance: main
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.23.0
    name: alertmanager-main
    namespace: kubesphere-monitoring-system
    resourceVersion: "72238388"
    uid: f1b5ecfc-a03e-4674-b3eb-802c653ce245
  subsets:
  - addresses:
    - ip: 192.168.3.218
      nodeName: zee8608workerapi02
      targetRef:
        kind: Pod
        name: alertmanager-main-1
        namespace: kubesphere-monitoring-system
        uid: ffb39224-d2f8-4be0-b2bd-859563f83d86
    - ip: 192.168.3.226
      nodeName: zee8608workerapi02
      targetRef:
        kind: Pod
        name: alertmanager-main-0
        namespace: kubesphere-monitoring-system
        uid: 69a9dff7-7b0c-4a0d-be2e-61c51f4ffeb4
    - ip: 192.168.5.204
      nodeName: zee8608workerapi01
      targetRef:
        kind: Pod
        name: alertmanager-main-2
        namespace: kubesphere-monitoring-system
        uid: feb7679e-c0b5-4589-a2e0-655776177f04
    ports:
    - name: reloader-web
      port: 8080
      protocol: TCP
    - name: web
      port: 9093
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-06-23T16:34:21Z"
    creationTimestamp: "2025-02-10T07:02:23Z"
    labels:
      operated-alertmanager: "true"
      service.kubernetes.io/headless: ""
    name: alertmanager-operated
    namespace: kubesphere-monitoring-system
    resourceVersion: "72238391"
    uid: 08141aab-3cc1-41ac-ab23-99b5f7b62857
  subsets:
  - addresses:
    - hostname: alertmanager-main-1
      ip: 192.168.3.218
      nodeName: zee8608workerapi02
      targetRef:
        kind: Pod
        name: alertmanager-main-1
        namespace: kubesphere-monitoring-system
        uid: ffb39224-d2f8-4be0-b2bd-859563f83d86
    - hostname: alertmanager-main-0
      ip: 192.168.3.226
      nodeName: zee8608workerapi02
      targetRef:
        kind: Pod
        name: alertmanager-main-0
        namespace: kubesphere-monitoring-system
        uid: 69a9dff7-7b0c-4a0d-be2e-61c51f4ffeb4
    - hostname: alertmanager-main-2
      ip: 192.168.5.204
      nodeName: zee8608workerapi01
      targetRef:
        kind: Pod
        name: alertmanager-main-2
        namespace: kubesphere-monitoring-system
        uid: feb7679e-c0b5-4589-a2e0-655776177f04
    ports:
    - name: udp-mesh
      port: 9094
      protocol: UDP
    - name: tcp-mesh
      port: 9094
      protocol: TCP
    - name: web
      port: 9093
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-02-10T07:02:13Z"
    labels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.6.0
      service.kubernetes.io/headless: ""
    name: kube-state-metrics
    namespace: kubesphere-monitoring-system
    resourceVersion: "70961411"
    uid: caafde9f-0f34-4ec7-8fac-1dfcc57a315f
  subsets:
  - addresses:
    - ip: 192.168.3.217
      nodeName: zee8608workerapi02
      targetRef:
        kind: Pod
        name: kube-state-metrics-99bf7fbb6-ntzsh
        namespace: kubesphere-monitoring-system
        uid: f3f763f4-39d4-4cb9-8a8b-533fd2a0c306
    ports:
    - name: https-main
      port: 8443
      protocol: TCP
    - name: https-self
      port: 9443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-02-10T07:02:11Z"
    labels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 1.3.1
      service.kubernetes.io/headless: ""
    name: node-exporter
    namespace: kubesphere-monitoring-system
    resourceVersion: "70961729"
    uid: 04b1dac2-23de-41e6-97cc-58c068874203
  subsets:
  - addresses:
    - ip: 10.48.219.135
      nodeName: zee8608masterapi01
      targetRef:
        kind: Pod
        name: node-exporter-9gthb
        namespace: kubesphere-monitoring-system
        uid: 51552759-cc7f-4e69-add3-70ae5c359f1d
    - ip: 10.48.219.136
      nodeName: zee8608masterapi02
      targetRef:
        kind: Pod
        name: node-exporter-b9qql
        namespace: kubesphere-monitoring-system
        uid: 4828d02c-182a-4078-b915-32e1f6168091
    - ip: 10.48.219.137
      nodeName: zee8608masterapi03
      targetRef:
        kind: Pod
        name: node-exporter-x78rx
        namespace: kubesphere-monitoring-system
        uid: f805c1a6-bfeb-4546-9c5d-b8f9c0772579
    - ip: 10.48.219.138
      nodeName: zee8608workerapi01
      targetRef:
        kind: Pod
        name: node-exporter-vks64
        namespace: kubesphere-monitoring-system
        uid: b03f74b7-8c0b-4f3e-b83e-549d5194817b
    - ip: 10.48.219.139
      nodeName: zee8608workerapi02
      targetRef:
        kind: Pod
        name: node-exporter-8c59f
        namespace: kubesphere-monitoring-system
        uid: 4bb0547b-4ec5-4925-addd-56866feacd41
    - ip: 10.48.219.140
      nodeName: zee8608workerapi03
      targetRef:
        kind: Pod
        name: node-exporter-2n9vd
        namespace: kubesphere-monitoring-system
        uid: f762f5dd-4952-477d-b56f-fd0a7a296e43
    ports:
    - name: https
      port: 9100
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-02-10T07:03:08Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      control-plane: controller-manager
    name: notification-manager-controller-metrics
    namespace: kubesphere-monitoring-system
    resourceVersion: "70961452"
    uid: d7191ed1-f4f5-4d38-8940-ed24c3d00897
  subsets:
  - addresses:
    - ip: 192.168.3.219
      nodeName: zee8608workerapi02
      targetRef:
        kind: Pod
        name: notification-manager-operator-9949f4878-x9vqw
        namespace: kubesphere-monitoring-system
        uid: 5686fda7-525b-4379-86f0-e0cd41e0125d
    ports:
    - name: https
      port: 8443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-06-23T16:33:53Z"
    creationTimestamp: "2025-02-10T07:03:20Z"
    labels:
      app: notification-manager
      notification-manager: notification-manager
    name: notification-manager-svc
    namespace: kubesphere-monitoring-system
    resourceVersion: "72238180"
    uid: c5a6b230-311e-458a-b8f5-e79258b0bad4
  subsets:
  - addresses:
    - ip: 192.168.3.224
      nodeName: zee8608workerapi02
      targetRef:
        kind: Pod
        name: notification-manager-deployment-c9d789f99-785kq
        namespace: kubesphere-monitoring-system
        uid: dff6d041-b68f-49d1-b17b-4c5324ca28a5
    - ip: 192.168.5.201
      nodeName: zee8608workerapi01
      targetRef:
        kind: Pod
        name: notification-manager-deployment-c9d789f99-4pw4l
        namespace: kubesphere-monitoring-system
        uid: 58ddbff9-54ec-4186-a067-a4812ae5f62e
    ports:
    - name: webhook
      port: 19093
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-02-10T07:03:08Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    name: notification-manager-webhook
    namespace: kubesphere-monitoring-system
    resourceVersion: "70961448"
    uid: 6f02480c-9512-47a1-896d-b5be0a2ac9e9
  subsets:
  - addresses:
    - ip: 192.168.3.219
      nodeName: zee8608workerapi02
      targetRef:
        kind: Pod
        name: notification-manager-operator-9949f4878-x9vqw
        namespace: kubesphere-monitoring-system
        uid: 5686fda7-525b-4379-86f0-e0cd41e0125d
    ports:
    - port: 9443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-06-23T16:39:44Z"
    creationTimestamp: "2025-02-10T07:02:15Z"
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.39.1
    name: prometheus-k8s
    namespace: kubesphere-monitoring-system
    resourceVersion: "72241138"
    uid: 5c763b38-fb1c-4b8d-8798-6e2eb87da234
  subsets:
  - addresses:
    - ip: 192.168.3.242
      nodeName: zee8608workerapi02
      targetRef:
        kind: Pod
        name: prometheus-k8s-1
        namespace: kubesphere-monitoring-system
        uid: b96580f1-5e2d-4d9b-b984-ee7ed9d830c6
    - ip: 192.168.5.228
      nodeName: zee8608workerapi01
      targetRef:
        kind: Pod
        name: prometheus-k8s-0
        namespace: kubesphere-monitoring-system
        uid: 601d7697-6e24-4ba3-a10d-79083ee01871
    ports:
    - name: reloader-web
      port: 8080
      protocol: TCP
    - name: web
      port: 9090
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-06-23T16:39:44Z"
    creationTimestamp: "2025-02-10T07:02:15Z"
    labels:
      operated-prometheus: "true"
      service.kubernetes.io/headless: ""
    name: prometheus-operated
    namespace: kubesphere-monitoring-system
    resourceVersion: "72241139"
    uid: bf3a1439-58fe-48c6-bf7b-2e2765506f6c
  subsets:
  - addresses:
    - hostname: prometheus-k8s-1
      ip: 192.168.3.242
      nodeName: zee8608workerapi02
      targetRef:
        kind: Pod
        name: prometheus-k8s-1
        namespace: kubesphere-monitoring-system
        uid: b96580f1-5e2d-4d9b-b984-ee7ed9d830c6
    - hostname: prometheus-k8s-0
      ip: 192.168.5.228
      nodeName: zee8608workerapi01
      targetRef:
        kind: Pod
        name: prometheus-k8s-0
        namespace: kubesphere-monitoring-system
        uid: 601d7697-6e24-4ba3-a10d-79083ee01871
    ports:
    - name: web
      port: 9090
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-06-23T16:34:31Z"
    creationTimestamp: "2025-02-10T07:01:55Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.55.1
      service.kubernetes.io/headless: ""
    name: prometheus-operator
    namespace: kubesphere-monitoring-system
    resourceVersion: "72238472"
    uid: 24914aa2-cbfc-4357-b061-80d4e2f309cf
  subsets:
  - addresses:
    - ip: 192.168.5.210
      nodeName: zee8608workerapi01
      targetRef:
        kind: Pod
        name: prometheus-operator-7888d46fbd-bxbr2
        namespace: kubesphere-monitoring-system
        uid: 164c6c58-96cf-4308-8012-c5ef3456d63f
    ports:
    - name: https
      port: 8443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-06-23T16:33:50Z"
    creationTimestamp: "2025-03-04T08:46:03Z"
    labels:
      app.kubernetes.io/component: thanos-ruler
      app.kubernetes.io/instance: kubesphere
      app.kubernetes.io/name: thanos-ruler
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.31.0
    name: thanos-ruler-kubesphere
    namespace: kubesphere-monitoring-system
    resourceVersion: "72238139"
    uid: f8111771-6cc4-4d70-a634-00eae837e679
  subsets:
  - addresses:
    - ip: 192.168.3.227
      nodeName: zee8608workerapi02
      targetRef:
        kind: Pod
        name: thanos-ruler-kubesphere-0
        namespace: kubesphere-monitoring-system
        uid: ff212f55-b536-4c2e-9b19-0e6d66e396d7
    - ip: 192.168.5.196
      nodeName: zee8608workerapi01
      targetRef:
        kind: Pod
        name: thanos-ruler-kubesphere-1
        namespace: kubesphere-monitoring-system
        uid: 387dd8a9-c3a4-440f-bbc3-6ec7170ea500
    ports:
    - name: web
      port: 10902
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-06-23T16:33:50Z"
    creationTimestamp: "2025-03-04T08:46:03Z"
    labels:
      operated-thanos-ruler: "true"
      service.kubernetes.io/headless: ""
    name: thanos-ruler-operated
    namespace: kubesphere-monitoring-system
    resourceVersion: "72238141"
    uid: 66776f1f-a4e8-47c2-9809-9b38ac300c2f
  subsets:
  - addresses:
    - ip: 192.168.3.227
      nodeName: zee8608workerapi02
      targetRef:
        kind: Pod
        name: thanos-ruler-kubesphere-0
        namespace: kubesphere-monitoring-system
        uid: ff212f55-b536-4c2e-9b19-0e6d66e396d7
    - ip: 192.168.5.196
      nodeName: zee8608workerapi01
      targetRef:
        kind: Pod
        name: thanos-ruler-kubesphere-1
        namespace: kubesphere-monitoring-system
        uid: 387dd8a9-c3a4-440f-bbc3-6ec7170ea500
    ports:
    - name: web
      port: 10902
      protocol: TCP
    - name: grpc
      port: 10901
      protocol: TCP
kind: List
metadata:
  resourceVersion: ""
