apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: notification-manager
      meta.helm.sh/release-namespace: kubesphere-monitoring-system
    creationTimestamp: "2025-02-10T07:03:07Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    name: notification-manager-leader-election-rolebinding
    namespace: kubesphere-monitoring-system
    resourceVersion: "1023656"
    uid: 4fdec7cf-65e0-4365-ad26-877ff6b50394
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: notification-manager-leader-election-role
  subjects:
  - kind: ServiceAccount
    name: notification-manager-sa
    namespace: kubesphere-monitoring-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"prometheus","app.kubernetes.io/instance":"k8s","app.kubernetes.io/name":"prometheus","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"2.39.1"},"name":"prometheus-k8s-config","namespace":"kubesphere-monitoring-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"prometheus-k8s-config"},"subjects":[{"kind":"ServiceAccount","name":"prometheus-k8s","namespace":"kubesphere-monitoring-system"}]}
    creationTimestamp: "2025-02-10T07:02:15Z"
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.39.1
    name: prometheus-k8s-config
    namespace: kubesphere-monitoring-system
    resourceVersion: "1022925"
    uid: a6f8b340-2690-4fa3-881e-faebfdad28cf
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-k8s-config
  subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: kubesphere-monitoring-system
kind: List
metadata:
  resourceVersion: ""
