apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"alert-router","app.kubernetes.io/instance":"main","app.kubernetes.io/name":"alertmanager","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"0.23.0"},"name":"alertmanager-main","namespace":"kubesphere-monitoring-system"}}
    creationTimestamp: "2025-02-10T07:02:21Z"
    labels:
      app.kubernetes.io/component: alert-router
      app.kubernetes.io/instance: main
      app.kubernetes.io/name: alertmanager
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.23.0
    name: alertmanager-main
    namespace: kubesphere-monitoring-system
    resourceVersion: "1023113"
    uid: 04e4b91d-84e3-4d93-b81b-b984a4d9cf53
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-02-10T06:55:41Z"
    name: default
    namespace: kubesphere-monitoring-system
    resourceVersion: "1020683"
    uid: 079946f2-cac0-49be-9569-c1e4a4092eeb
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"exporter","app.kubernetes.io/name":"kube-state-metrics","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"2.6.0"},"name":"kube-state-metrics","namespace":"kubesphere-monitoring-system"}}
    creationTimestamp: "2025-02-10T07:02:11Z"
    labels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.6.0
    name: kube-state-metrics
    namespace: kubesphere-monitoring-system
    resourceVersion: "1022892"
    uid: 0e06b6eb-7f2e-4f7c-9842-30263d0e1123
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"exporter","app.kubernetes.io/name":"node-exporter","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"1.3.1"},"name":"node-exporter","namespace":"kubesphere-monitoring-system"}}
    creationTimestamp: "2025-02-10T07:02:09Z"
    labels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: node-exporter
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 1.3.1
    name: node-exporter
    namespace: kubesphere-monitoring-system
    resourceVersion: "1022821"
    uid: 0c29bc2d-fac2-44bc-b569-eb42721d9e92
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: notification-manager
      meta.helm.sh/release-namespace: kubesphere-monitoring-system
    creationTimestamp: "2025-02-10T07:02:49Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    name: notification-manager-sa
    namespace: kubesphere-monitoring-system
    resourceVersion: "1023452"
    uid: d1c76661-82a3-4dc5-b5db-f4a647146dc8
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"prometheus","app.kubernetes.io/instance":"k8s","app.kubernetes.io/name":"prometheus","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"2.39.1"},"name":"prometheus-k8s","namespace":"kubesphere-monitoring-system"}}
    creationTimestamp: "2025-02-10T07:02:15Z"
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.39.1
    name: prometheus-k8s
    namespace: kubesphere-monitoring-system
    resourceVersion: "1022940"
    uid: e1850912-ed13-42c7-910b-6af41198963f
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"controller","app.kubernetes.io/name":"prometheus-operator","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"0.55.1"},"name":"prometheus-operator","namespace":"kubesphere-monitoring-system"}}
    creationTimestamp: "2025-02-10T07:02:00Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 0.55.1
    name: prometheus-operator
    namespace: kubesphere-monitoring-system
    resourceVersion: "1022737"
    uid: be3743c2-91bf-433a-8f03-0a5e867e7008
kind: List
metadata:
  resourceVersion: ""
