apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2025-02-07T07:59:14Z"
    labels:
      endpointslice.kubernetes.io/skip-mirror: "true"
    name: kubernetes
    namespace: default
    resourceVersion: "119478761"
    uid: 0b661de6-5be2-4881-9871-d7752fc3589e
  subsets:
  - addresses:
    - ip: 10.48.219.135
    - ip: 10.48.219.136
    - ip: 10.48.219.137
    ports:
    - name: https
      port: 6443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2025-06-23T16:39:19Z"
    creationTimestamp: "2025-05-30T11:16:17Z"
    labels:
      app: productmaster-mongodb-svc
    name: productmaster-mongodb-svc
    namespace: default
    resourceVersion: "72241061"
    uid: e2936ef2-d5b3-4980-8e8e-6ebb33d93373
  subsets:
  - addresses:
    - hostname: productmaster-mongodb-0
      ip: 192.168.5.230
      nodeName: zee8608workerapi01
      targetRef:
        kind: Pod
        name: productmaster-mongodb-0
        namespace: default
        uid: 351eda94-88be-4bd4-8055-b01688cc1df2
    ports:
    - name: mongodb
      port: 27017
      protocol: TCP
kind: List
metadata:
  resourceVersion: ""
