apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-02-07T07:59:14Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "193"
    uid: 098d130f-3dfb-4c13-9177-e9d5bc4e60d3
  spec:
    clusterIP: 10.96.0.1
    clusterIPs:
    - 10.96.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"productmaster-mongodb-svc"},"name":"productmaster-mongodb-svc","namespace":"default","ownerReferences":[{"apiVersion":"mongodbcommunity.mongodb.com/v1","blockOwnerDeletion":true,"controller":true,"kind":"MongoDBCommunity","name":"productmaster-mongodb","uid":"196240d6-7f68-445c-83d7-c5d00f16e445"}],"resourceVersion":"36271195","uid":"90f471d8-9474-486c-a5f4-f633b697d8a1"},"spec":{"allocateLoadBalancerNodePorts":true,"clusterIP":"10.100.0.129","clusterIPs":["10.100.0.129"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"mongodb","nodePort":31881,"port":27017,"protocol":"TCP","targetPort":27017}],"publishNotReadyAddresses":true,"selector":{"app":"productmaster-mongodb-svc"},"sessionAffinity":"None","type":"LoadBalancer"},"status":{"loadBalancer":{"ingress":[{"ip":"10.48.219.175","ipMode":"VIP"}]}}}
      metallb.io/ip-allocated-from-pool: first-pool
    creationTimestamp: "2025-05-30T11:16:48Z"
    labels:
      app: productmaster-mongodb-svc
    name: productmaster-mongodb-svc
    namespace: default
    ownerReferences:
    - apiVersion: mongodbcommunity.mongodb.com/v1
      blockOwnerDeletion: true
      controller: true
      kind: MongoDBCommunity
      name: productmaster-mongodb
      uid: 196240d6-7f68-445c-83d7-c5d00f16e445
    resourceVersion: "59796616"
    uid: 88b1cd5c-5cf9-495c-a950-089d445019ac
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.100.0.129
    clusterIPs:
    - 10.100.0.129
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: mongodb
      nodePort: 31881
      port: 27017
      protocol: TCP
      targetPort: 27017
    publishNotReadyAddresses: true
    selector:
      app: productmaster-mongodb-svc
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 10.48.219.174
        ipMode: VIP
kind: List
metadata:
  resourceVersion: ""
