apiVersion: v1
items:
- apiVersion: logging.kubesphere.io/v1alpha2
  kind: FluentBit
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"logging.kubesphere.io/v1alpha2","kind":"FluentBit","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"fluent-bit"},"name":"fluent-bit","namespace":"kubesphere-logging-system"},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"node-role.kubernetes.io/edge","operator":"DoesNotExist"}]}]}}},"fluentBitConfigName":"fluent-bit-config","image":"kubesphere/fluent-bit:v1.9.4","positionDB":{"emptyDir":{}},"resources":{"limits":{"cpu":"500m","memory":"200Mi"},"requests":{"cpu":"10m","memory":"25Mi"}},"tolerations":[{"operator":"Exists"}]}}
    creationTimestamp: "2025-03-04T08:41:08Z"
    finalizers:
    - fluentbit.logging.kubesphere.io
    generation: 2
    labels:
      app.kubernetes.io/name: fluent-bit
    name: fluent-bit
    namespace: kubesphere-logging-system
    resourceVersion: "11875295"
    uid: cb909d46-512e-480d-b157-4fbd14303911
  spec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/edge
              operator: DoesNotExist
    fluentBitConfigName: fluent-bit-config
    image: kubesphere/fluent-bit:v1.9.4
    positionDB:
      emptyDir: {}
    resources:
      limits:
        cpu: 500m
        memory: 200Mi
      requests:
        cpu: 10m
        memory: 25Mi
    tolerations:
    - operator: Exists
  status: {}
kind: List
metadata:
  resourceVersion: ""
