apiVersion: v1
items:
- apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      batch.kubernetes.io/cronjob-scheduled-timestamp: "2025-06-23T01:00:00Z"
      revisions: '{"1":{"status":"failed","reasons":["BackoffLimitExceeded"],"messages":["Job
        has reached the specified backoff limit"],"desire":1,"failed":7,"uid":"f8af59f5-76d9-45b3-8704-60944d4f82ea","start-time":"2025-06-23T06:30:00+05:30","completion-time":"0001-01-01T00:00:00Z"}}'
    creationTimestamp: "2025-06-23T01:00:00Z"
    generation: 1
    labels:
      app: opensearch-curator
      release: opensearch-logging-curator
    name: opensearch-logging-curator-opensearch-curator-29177340
    namespace: kubesphere-logging-system
    ownerReferences:
    - apiVersion: batch/v1
      blockOwnerDeletion: true
      controller: true
      kind: CronJob
      name: opensearch-logging-curator-opensearch-curator
      uid: 4d45e377-2d0e-43cc-8ca5-2841cdc26d3c
    resourceVersion: "71945675"
    uid: f8af59f5-76d9-45b3-8704-60944d4f82ea
  spec:
    backoffLimit: 6
    completionMode: NonIndexed
    completions: 1
    manualSelector: false
    parallelism: 1
    podReplacementPolicy: TerminatingOrFailed
    selector:
      matchLabels:
        batch.kubernetes.io/controller-uid: f8af59f5-76d9-45b3-8704-60944d4f82ea
    suspend: false
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: opensearch-curator
          batch.kubernetes.io/controller-uid: f8af59f5-76d9-45b3-8704-60944d4f82ea
          batch.kubernetes.io/job-name: opensearch-logging-curator-opensearch-curator-29177340
          controller-uid: f8af59f5-76d9-45b3-8704-60944d4f82ea
          job-name: opensearch-logging-curator-opensearch-curator-29177340
          release: opensearch-logging-curator
      spec:
        containers:
        - args:
          - --config
          - /etc/opensearch-curator/config.yml
          - /etc/opensearch-curator/action_file.yml
          command:
          - curator/curator
          image: kubesphere/opensearch-curator:v0.0.5
          imagePullPolicy: IfNotPresent
          name: opensearch-curator
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/opensearch-curator
            name: config-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Never
        schedulerName: default-scheduler
        securityContext:
          runAsUser: 16
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: opensearch-logging-curator-opensearch-curator-config
          name: config-volume
  status:
    conditions:
    - lastProbeTime: "2025-06-23T01:10:09Z"
      lastTransitionTime: "2025-06-23T01:10:09Z"
      message: Job has reached the specified backoff limit
      reason: BackoffLimitExceeded
      status: "True"
      type: Failed
    failed: 7
    ready: 0
    startTime: "2025-06-23T01:00:01Z"
    terminating: 0
    uncountedTerminatedPods: {}
- apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      batch.kubernetes.io/cronjob-scheduled-timestamp: "2025-10-01T01:00:00Z"
    creationTimestamp: "2025-10-01T01:00:00Z"
    generation: 1
    labels:
      app: opensearch-curator
      release: opensearch-logging-curator
    name: opensearch-logging-curator-opensearch-curator-29321340
    namespace: kubesphere-logging-system
    ownerReferences:
    - apiVersion: batch/v1
      blockOwnerDeletion: true
      controller: true
      kind: CronJob
      name: opensearch-logging-curator-opensearch-curator
      uid: 4d45e377-2d0e-43cc-8ca5-2841cdc26d3c
    resourceVersion: "121876907"
    uid: 78f168a6-8c4c-4e97-a9ff-f9c352696683
  spec:
    backoffLimit: 6
    completionMode: NonIndexed
    completions: 1
    manualSelector: false
    parallelism: 1
    podReplacementPolicy: TerminatingOrFailed
    selector:
      matchLabels:
        batch.kubernetes.io/controller-uid: 78f168a6-8c4c-4e97-a9ff-f9c352696683
    suspend: false
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: opensearch-curator
          batch.kubernetes.io/controller-uid: 78f168a6-8c4c-4e97-a9ff-f9c352696683
          batch.kubernetes.io/job-name: opensearch-logging-curator-opensearch-curator-29321340
          controller-uid: 78f168a6-8c4c-4e97-a9ff-f9c352696683
          job-name: opensearch-logging-curator-opensearch-curator-29321340
          release: opensearch-logging-curator
      spec:
        containers:
        - args:
          - --config
          - /etc/opensearch-curator/config.yml
          - /etc/opensearch-curator/action_file.yml
          command:
          - curator/curator
          image: kubesphere/opensearch-curator:v0.0.5
          imagePullPolicy: IfNotPresent
          name: opensearch-curator
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/opensearch-curator
            name: config-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Never
        schedulerName: default-scheduler
        securityContext:
          runAsUser: 16
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: opensearch-logging-curator-opensearch-curator-config
          name: config-volume
  status:
    completionTime: "2025-10-01T01:00:04Z"
    conditions:
    - lastProbeTime: "2025-10-01T01:00:04Z"
      lastTransitionTime: "2025-10-01T01:00:04Z"
      status: "True"
      type: Complete
    ready: 0
    startTime: "2025-10-01T01:00:00Z"
    succeeded: 1
    terminating: 0
    uncountedTerminatedPods: {}
- apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      batch.kubernetes.io/cronjob-scheduled-timestamp: "2025-10-02T01:00:00Z"
    creationTimestamp: "2025-10-02T01:00:00Z"
    generation: 1
    labels:
      app: opensearch-curator
      release: opensearch-logging-curator
    name: opensearch-logging-curator-opensearch-curator-29322780
    namespace: kubesphere-logging-system
    ownerReferences:
    - apiVersion: batch/v1
      blockOwnerDeletion: true
      controller: true
      kind: CronJob
      name: opensearch-logging-curator-opensearch-curator
      uid: 4d45e377-2d0e-43cc-8ca5-2841cdc26d3c
    resourceVersion: "122357066"
    uid: a43b494b-5438-4653-a43b-139d91636b54
  spec:
    backoffLimit: 6
    completionMode: NonIndexed
    completions: 1
    manualSelector: false
    parallelism: 1
    podReplacementPolicy: TerminatingOrFailed
    selector:
      matchLabels:
        batch.kubernetes.io/controller-uid: a43b494b-5438-4653-a43b-139d91636b54
    suspend: false
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: opensearch-curator
          batch.kubernetes.io/controller-uid: a43b494b-5438-4653-a43b-139d91636b54
          batch.kubernetes.io/job-name: opensearch-logging-curator-opensearch-curator-29322780
          controller-uid: a43b494b-5438-4653-a43b-139d91636b54
          job-name: opensearch-logging-curator-opensearch-curator-29322780
          release: opensearch-logging-curator
      spec:
        containers:
        - args:
          - --config
          - /etc/opensearch-curator/config.yml
          - /etc/opensearch-curator/action_file.yml
          command:
          - curator/curator
          image: kubesphere/opensearch-curator:v0.0.5
          imagePullPolicy: IfNotPresent
          name: opensearch-curator
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/opensearch-curator
            name: config-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Never
        schedulerName: default-scheduler
        securityContext:
          runAsUser: 16
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: opensearch-logging-curator-opensearch-curator-config
          name: config-volume
  status:
    completionTime: "2025-10-02T01:00:04Z"
    conditions:
    - lastProbeTime: "2025-10-02T01:00:04Z"
      lastTransitionTime: "2025-10-02T01:00:04Z"
      status: "True"
      type: Complete
    ready: 0
    startTime: "2025-10-02T01:00:00Z"
    succeeded: 1
    terminating: 0
    uncountedTerminatedPods: {}
- apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      batch.kubernetes.io/cronjob-scheduled-timestamp: "2025-10-03T01:00:00Z"
    creationTimestamp: "2025-10-03T01:00:00Z"
    generation: 1
    labels:
      app: opensearch-curator
      release: opensearch-logging-curator
    name: opensearch-logging-curator-opensearch-curator-29324220
    namespace: kubesphere-logging-system
    ownerReferences:
    - apiVersion: batch/v1
      blockOwnerDeletion: true
      controller: true
      kind: CronJob
      name: opensearch-logging-curator-opensearch-curator
      uid: 4d45e377-2d0e-43cc-8ca5-2841cdc26d3c
    resourceVersion: "122838024"
    uid: 5445bb3a-7625-4ffd-b0d8-b5bdfb8de1b8
  spec:
    backoffLimit: 6
    completionMode: NonIndexed
    completions: 1
    manualSelector: false
    parallelism: 1
    podReplacementPolicy: TerminatingOrFailed
    selector:
      matchLabels:
        batch.kubernetes.io/controller-uid: 5445bb3a-7625-4ffd-b0d8-b5bdfb8de1b8
    suspend: false
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: opensearch-curator
          batch.kubernetes.io/controller-uid: 5445bb3a-7625-4ffd-b0d8-b5bdfb8de1b8
          batch.kubernetes.io/job-name: opensearch-logging-curator-opensearch-curator-29324220
          controller-uid: 5445bb3a-7625-4ffd-b0d8-b5bdfb8de1b8
          job-name: opensearch-logging-curator-opensearch-curator-29324220
          release: opensearch-logging-curator
      spec:
        containers:
        - args:
          - --config
          - /etc/opensearch-curator/config.yml
          - /etc/opensearch-curator/action_file.yml
          command:
          - curator/curator
          image: kubesphere/opensearch-curator:v0.0.5
          imagePullPolicy: IfNotPresent
          name: opensearch-curator
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/opensearch-curator
            name: config-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Never
        schedulerName: default-scheduler
        securityContext:
          runAsUser: 16
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: opensearch-logging-curator-opensearch-curator-config
          name: config-volume
  status:
    completionTime: "2025-10-03T01:00:04Z"
    conditions:
    - lastProbeTime: "2025-10-03T01:00:04Z"
      lastTransitionTime: "2025-10-03T01:00:04Z"
      status: "True"
      type: Complete
    ready: 0
    startTime: "2025-10-03T01:00:00Z"
    succeeded: 1
    terminating: 0
    uncountedTerminatedPods: {}
kind: List
metadata:
  resourceVersion: ""
