apiVersion: v1
items:
- apiVersion: logging.kubesphere.io/v1alpha2
  kind: Output
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"logging.kubesphere.io/v1alpha2","kind":"Output","metadata":{"annotations":{},"labels":{"logging.kubesphere.io/component":"auditing","logging.kubesphere.io/enabled":"true"},"name":"opensearch-auditing","namespace":"kubesphere-logging-system"},"spec":{"match":"kube_auditing","opensearch":{"host":"opensearch-cluster-data.kubesphere-logging-system.svc","httpPassword":{"valueFrom":{"secretKeyRef":{"key":"password","name":"opensearch-credentials"}}},"httpUser":{"valueFrom":{"secretKeyRef":{"key":"username","name":"opensearch-credentials"}}},"logstashFormat":true,"logstashPrefix":"ks-whizard-auditing","port":9200,"suppressTypeName":true,"tls":{"verify":false}}}}
    creationTimestamp: "2025-03-04T08:44:19Z"
    generation: 1
    labels:
      logging.kubesphere.io/component: auditing
      logging.kubesphere.io/enabled: "true"
    name: opensearch-auditing
    namespace: kubesphere-logging-system
    resourceVersion: "11876626"
    uid: 0a8fcbe0-3b8d-4a30-9647-52e717baf63b
  spec:
    match: kube_auditing
    opensearch:
      host: opensearch-cluster-data.kubesphere-logging-system.svc
      httpPassword:
        valueFrom:
          secretKeyRef:
            key: password
            name: opensearch-credentials
      httpUser:
        valueFrom:
          secretKeyRef:
            key: username
            name: opensearch-credentials
      logstashFormat: true
      logstashPrefix: ks-whizard-auditing
      port: 9200
      suppressTypeName: true
      tls:
        verify: false
kind: List
metadata:
  resourceVersion: ""
