apiVersion: v1
items:
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    annotations:
      meta.helm.sh/release-name: opensearch-data
      meta.helm.sh/release-namespace: kubesphere-logging-system
    creationTimestamp: "2025-03-04T08:40:52Z"
    generation: 1
    labels:
      app.kubernetes.io/component: opensearch-cluster-data
      app.kubernetes.io/instance: opensearch-data
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: opensearch
      app.kubernetes.io/version: 2.6.0
      helm.sh/chart: opensearch-2.11.0
    name: opensearch-cluster-data-pdb
    namespace: kubesphere-logging-system
    resourceVersion: "72247724"
    uid: 4193d4b0-c6f7-4c48-929f-7bc3506a62d5
  spec:
    maxUnavailable: 1
    selector:
      matchLabels:
        app.kubernetes.io/instance: opensearch-data
        app.kubernetes.io/name: opensearch
  status:
    conditions:
    - lastTransitionTime: "2025-06-23T16:50:31Z"
      message: ""
      observedGeneration: 1
      reason: SufficientPods
      status: "True"
      type: DisruptionAllowed
    currentHealthy: 2
    desiredHealthy: 1
    disruptionsAllowed: 1
    expectedPods: 2
    observedGeneration: 1
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    annotations:
      meta.helm.sh/release-name: opensearch-master
      meta.helm.sh/release-namespace: kubesphere-logging-system
    creationTimestamp: "2025-03-04T08:40:41Z"
    generation: 1
    labels:
      app.kubernetes.io/component: opensearch-cluster-master
      app.kubernetes.io/instance: opensearch-master
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: opensearch
      app.kubernetes.io/version: 2.6.0
      helm.sh/chart: opensearch-2.11.0
    name: opensearch-cluster-master-pdb
    namespace: kubesphere-logging-system
    resourceVersion: "72247665"
    uid: d9ae9255-b05d-4ed2-9a7d-9555051039cf
  spec:
    maxUnavailable: 1
    selector:
      matchLabels:
        app.kubernetes.io/instance: opensearch-master
        app.kubernetes.io/name: opensearch
  status:
    conditions:
    - lastTransitionTime: "2025-06-23T16:50:26Z"
      message: ""
      observedGeneration: 1
      reason: SufficientPods
      status: "True"
      type: DisruptionAllowed
    currentHealthy: 3
    desiredHealthy: 2
    disruptionsAllowed: 1
    expectedPods: 3
    observedGeneration: 1
kind: List
metadata:
  resourceVersion: ""
