apiVersion: v1
items:
- apiVersion: v1
  data:
    client-max-body-size: 200m
    proxy-body-size: 200m
    proxy-read-timeout: "300"
    proxy-send-timeout: "300"
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: ingress-nginx
      meta.helm.sh/release-namespace: ingress-nginx
    creationTimestamp: "2025-02-13T08:12:54Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.12.0
      helm.sh/chart: ingress-nginx-4.12.0
    name: ingress-nginx-controller
    namespace: ingress-nginx
    resourceVersion: "66726798"
    uid: 548f4925-c0cf-432f-af52-cd99284a10cc
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIIBGpEgb8zVRswDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
      AxMKa3ViZXJuZXRlczAeFw0yNTAyMDcwNzU0MDZaFw0zNTAyMDUwNzU5MDZaMBUx
      EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQDcKXkUtHMKM7qeci7OlLNez2FlydMAt9l6KKkywvtuLyaMIrJKbFPh8hml
      H2dnMm7PRXcy/xoZFucFHfjaUY+euYJ6cf3MAoQfG/SfgpA5TRqEPbdxwc+GHDy7
      6ZoH9gIYHLkdeRUw0QTKKZTNYmRhRZ7oLjRmssL0kSpWOrg3EdN/K95ZT4eczUrl
      ts/rLLJPILP6LuWGllkIqnKBpm95RbpeGfTCoCAYbYIpbm0XzbybHeJuar+mA2kG
      Vhv8LJH9HIUCPTPLY4eUNFM5yAOlqR4p2tKpIHcaQC8WZhJqQBd3/OLx1fDnEsu5
      KCg99V39QHNmXONGKNdVZdnvCa8DAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
      BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRSbsFhjuaavB3D2AJAgY6/Kg93NDAV
      BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQBtFumnVigF
      ZqgHe3ok8jdx/o48sBfKM+N+eiqEKsuVuWhiYcMGhlXqqvgX5qHDcM+QPC2x4QxE
      NiZ0beIXwVs/xeOx9KeoPfnem58Ke51qlCBiTZrPTFhCIGUfqpD9SAxFRXX/4Re+
      ff8hORHxXHM+mo9fRUIsDkEON3IoFbImuq0bfklHbPfFJ1z+f/Fg+3bG4bUcMRDG
      /N3BorYqcnQxsvXlZpw3yDQrm3VukCTZSKm3FAuakJlBntmxHM4UewnN0VaF8ZAR
      dfz/NBVYyrEu/zPNPOYYHVLLfcMPbtlxnCnQuBB5C6Bv0hH1YNcwvEObxZH4+8G0
      O6YN95NGdZMw
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2025-02-13T08:12:44Z"
    name: kube-root-ca.crt
    namespace: ingress-nginx
    resourceVersion: "2538773"
    uid: 63b9a5fa-09df-45be-adbf-ba89660a31ef
- apiVersion: v1
  data:
    "6379": redis/redis:6379
    "27017": default/productmaster-mongodb-svc:27017
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"27017":"default/productmaster-mongodb-svc:27017","stream-snippet":"server {\n  listen 27017;\n  proxy_pass kubapimongo.zeelearn.com;\n  allow 115.124.114.88/32;\n  deny all;\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"mongo-tcp-services","namespace":"ingress-nginx"}}
    creationTimestamp: "2025-04-17T05:49:32Z"
    name: mongo-tcp-services
    namespace: ingress-nginx
    resourceVersion: "38489206"
    uid: bf853d92-a8ef-47ea-b61d-f0412015fbe6
- apiVersion: v1
  data:
    "6379": redis/redis:6379
  kind: ConfigMap
  metadata:
    creationTimestamp: "2025-04-17T07:04:36Z"
    name: redis-tcp-services
    namespace: ingress-nginx
    resourceVersion: "36280335"
    uid: 93a83bbf-e61f-4974-90c8-e5a5359a88c1
kind: List
metadata:
  resourceVersion: ""
