apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: ingress-nginx
      meta.helm.sh/release-namespace: ingress-nginx
      metallb.io/ip-allocated-from-pool: first-pool
    creationTimestamp: "2025-02-13T08:12:54Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.12.0
      helm.sh/chart: ingress-nginx-4.12.0
    name: ingress-nginx-controller
    namespace: ingress-nginx
    resourceVersion: "36238330"
    uid: 1b7c51b3-ac47-4293-8477-ceab2419f67c
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.102.186.10
    clusterIPs:
    - 10.102.186.10
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    loadBalancerIP: 10.48.219.171
    ports:
    - appProtocol: http
      name: http
      nodePort: 31390
      port: 80
      protocol: TCP
      targetPort: http
    - appProtocol: https
      name: https
      nodePort: 30899
      port: 443
      protocol: TCP
      targetPort: https
    - name: redis-proxied-tcp
      nodePort: 30703
      port: 6379
      protocol: TCP
      targetPort: 6379
    - name: mongo-proxied-tcp
      nodePort: 30704
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 10.48.219.171
        ipMode: VIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: ingress-nginx
      meta.helm.sh/release-namespace: ingress-nginx
    creationTimestamp: "2025-02-13T08:12:54Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: 1.12.0
      helm.sh/chart: ingress-nginx-4.12.0
    name: ingress-nginx-controller-admission
    namespace: ingress-nginx
    resourceVersion: "2538872"
    uid: 7d9d0522-eecf-4a46-8c21-f4fc7b242d90
  spec:
    clusterIP: 10.98.229.192
    clusterIPs:
    - 10.98.229.192
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - appProtocol: https
      name: https-webhook
      port: 443
      protocol: TCP
      targetPort: webhook
    selector:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
