apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"app":"cert-manager","app.kubernetes.io/component":"controller","app.kubernetes.io/instance":"cert-manager","app.kubernetes.io/name":"cert-manager","app.kubernetes.io/version":"v1.17.0"},"name":"cert-manager-cert-manager-tokenrequest","namespace":"cert-manager"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"cert-manager-tokenrequest"},"subjects":[{"kind":"ServiceAccount","name":"cert-manager","namespace":"cert-manager"}]}
    creationTimestamp: "2025-02-08T18:54:49Z"
    labels:
      app: cert-manager
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/version: v1.17.0
    name: cert-manager-cert-manager-tokenrequest
    namespace: cert-manager
    resourceVersion: "480425"
    uid: 585df4d4-b4fb-4652-898a-75c041d61854
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: cert-manager-tokenrequest
  subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"app":"webhook","app.kubernetes.io/component":"webhook","app.kubernetes.io/instance":"cert-manager","app.kubernetes.io/name":"webhook","app.kubernetes.io/version":"v1.17.0"},"name":"cert-manager-webhook:dynamic-serving","namespace":"cert-manager"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"cert-manager-webhook:dynamic-serving"},"subjects":[{"kind":"ServiceAccount","name":"cert-manager-webhook","namespace":"cert-manager"}]}
    creationTimestamp: "2025-02-08T18:54:49Z"
    labels:
      app: webhook
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/name: webhook
      app.kubernetes.io/version: v1.17.0
    name: cert-manager-webhook:dynamic-serving
    namespace: cert-manager
    resourceVersion: "480426"
    uid: 120af22e-e014-417e-875c-c55d18328cc2
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: cert-manager-webhook:dynamic-serving
  subjects:
  - kind: ServiceAccount
    name: cert-manager-webhook
    namespace: cert-manager
kind: List
metadata:
  resourceVersion: ""
